// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/graphops.proto

package graphopspb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphOpsService_ExecuteQuery_FullMethodName       = "/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteQuery"
	GraphOpsService_ExecuteTransaction_FullMethodName = "/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteTransaction"
	GraphOpsService_HealthCheck_FullMethodName        = "/ninaivalaigal.graphops.v1.GraphOpsService/HealthCheck"
	GraphOpsService_GetGraphStats_FullMethodName      = "/ninaivalaigal.graphops.v1.GraphOpsService/GetGraphStats"
)

// GraphOpsServiceClient is the client API for GraphOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GraphOps Service - gRPC definitions
type GraphOpsServiceClient interface {
	// Execute a Cypher query
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	// Execute multiple queries in a transaction
	ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Get graph statistics
	GetGraphStats(ctx context.Context, in *GetGraphStatsRequest, opts ...grpc.CallOption) (*GetGraphStatsResponse, error)
}

type graphOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphOpsServiceClient(cc grpc.ClientConnInterface) GraphOpsServiceClient {
	return &graphOpsServiceClient{cc}
}

func (c *graphOpsServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTransactionResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_ExecuteTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) GetGraphStats(ctx context.Context, in *GetGraphStatsRequest, opts ...grpc.CallOption) (*GetGraphStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGraphStatsResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_GetGraphStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphOpsServiceServer is the server API for GraphOpsService service.
// All implementations must embed UnimplementedGraphOpsServiceServer
// for forward compatibility.
//
// GraphOps Service - gRPC definitions
type GraphOpsServiceServer interface {
	// Execute a Cypher query
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	// Execute multiple queries in a transaction
	ExecuteTransaction(context.Context, *ExecuteTransactionRequest) (*ExecuteTransactionResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Get graph statistics
	GetGraphStats(context.Context, *GetGraphStatsRequest) (*GetGraphStatsResponse, error)
	mustEmbedUnimplementedGraphOpsServiceServer()
}

// UnimplementedGraphOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphOpsServiceServer struct{}

func (UnimplementedGraphOpsServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedGraphOpsServiceServer) ExecuteTransaction(context.Context, *ExecuteTransactionRequest) (*ExecuteTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTransaction not implemented")
}
func (UnimplementedGraphOpsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGraphOpsServiceServer) GetGraphStats(context.Context, *GetGraphStatsRequest) (*GetGraphStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGraphStats not implemented")
}
func (UnimplementedGraphOpsServiceServer) mustEmbedUnimplementedGraphOpsServiceServer() {}
func (UnimplementedGraphOpsServiceServer) testEmbeddedByValue()                         {}

// UnsafeGraphOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphOpsServiceServer will
// result in compilation errors.
type UnsafeGraphOpsServiceServer interface {
	mustEmbedUnimplementedGraphOpsServiceServer()
}

func RegisterGraphOpsServiceServer(s grpc.ServiceRegistrar, srv GraphOpsServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraphOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphOpsService_ServiceDesc, srv)
}

func _GraphOpsService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_ExecuteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).ExecuteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_ExecuteTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).ExecuteTransaction(ctx, req.(*ExecuteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_GetGraphStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGraphStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).GetGraphStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_GetGraphStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).GetGraphStats(ctx, req.(*GetGraphStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphOpsService_ServiceDesc is the grpc.ServiceDesc for GraphOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ninaivalaigal.graphops.v1.GraphOpsService",
	HandlerType: (*GraphOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _GraphOpsService_ExecuteQuery_Handler,
		},
		{
			MethodName: "ExecuteTransaction",
			Handler:    _GraphOpsService_ExecuteTransaction_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GraphOpsService_HealthCheck_Handler,
		},
		{
			MethodName: "GetGraphStats",
			Handler:    _GraphOpsService_GetGraphStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/graphops.proto",
}
