// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/graphops.proto

package graphopspb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Execute Query
type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // for access control
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_proto_graphops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecuteQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Metadata      *QueryMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_proto_graphops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteQueryResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteQueryResponse) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteQueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*QueryColumn         `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*QueryRow            `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_proto_graphops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetColumns() []*QueryColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResult) GetRows() []*QueryRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type QueryColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryColumn) Reset() {
	*x = QueryColumn{}
	mi := &file_proto_graphops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryColumn) ProtoMessage() {}

func (x *QueryColumn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryColumn.ProtoReflect.Descriptor instead.
func (*QueryColumn) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{3}
}

func (x *QueryColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryColumn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type QueryRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*QueryValue          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRow) Reset() {
	*x = QueryRow{}
	mi := &file_proto_graphops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRow) ProtoMessage() {}

func (x *QueryRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRow.ProtoReflect.Descriptor instead.
func (*QueryRow) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRow) GetValues() []*QueryValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type QueryValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*QueryValue_StringValue
	//	*QueryValue_IntValue
	//	*QueryValue_DoubleValue
	//	*QueryValue_BoolValue
	//	*QueryValue_JsonValue
	Value         isQueryValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryValue) Reset() {
	*x = QueryValue{}
	mi := &file_proto_graphops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValue) ProtoMessage() {}

func (x *QueryValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValue.ProtoReflect.Descriptor instead.
func (*QueryValue) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{5}
}

func (x *QueryValue) GetValue() isQueryValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *QueryValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*QueryValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *QueryValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*QueryValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *QueryValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*QueryValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *QueryValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*QueryValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *QueryValue) GetJsonValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*QueryValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return nil
}

type isQueryValue_Value interface {
	isQueryValue_Value()
}

type QueryValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type QueryValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type QueryValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type QueryValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type QueryValue_JsonValue struct {
	JsonValue []byte `protobuf:"bytes,5,opt,name=json_value,json=jsonValue,proto3,oneof"` // for complex objects
}

func (*QueryValue_StringValue) isQueryValue_Value() {}

func (*QueryValue_IntValue) isQueryValue_Value() {}

func (*QueryValue_DoubleValue) isQueryValue_Value() {}

func (*QueryValue_BoolValue) isQueryValue_Value() {}

func (*QueryValue_JsonValue) isQueryValue_Value() {}

type QueryMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RowsAffected    int32                  `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ExecutionTimeMs int32                  `protobuf:"varint,2,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	QueryPlan       string                 `protobuf:"bytes,3,opt,name=query_plan,json=queryPlan,proto3" json:"query_plan,omitempty"`
	Warnings        []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_proto_graphops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{6}
}

func (x *QueryMetadata) GetRowsAffected() int32 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryMetadata) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *QueryMetadata) GetQueryPlan() string {
	if x != nil {
		return x.QueryPlan
	}
	return ""
}

func (x *QueryMetadata) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Execute Transaction
type ExecuteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionRequest) Reset() {
	*x = ExecuteTransactionRequest{}
	mi := &file_proto_graphops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionRequest) ProtoMessage() {}

func (x *ExecuteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteTransactionRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ExecuteTransactionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteTransactionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ExecuteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueryResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Metadata      *TransactionMetadata   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionResponse) Reset() {
	*x = ExecuteTransactionResponse{}
	mi := &file_proto_graphops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionResponse) ProtoMessage() {}

func (x *ExecuteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteTransactionResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteTransactionResponse) GetMetadata() *TransactionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransactionMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalQueries         int32                  `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	SuccessfulQueries    int32                  `protobuf:"varint,2,opt,name=successful_queries,json=successfulQueries,proto3" json:"successful_queries,omitempty"`
	TotalExecutionTimeMs int32                  `protobuf:"varint,3,opt,name=total_execution_time_ms,json=totalExecutionTimeMs,proto3" json:"total_execution_time_ms,omitempty"`
	Committed            bool                   `protobuf:"varint,4,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TransactionMetadata) Reset() {
	*x = TransactionMetadata{}
	mi := &file_proto_graphops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMetadata) ProtoMessage() {}

func (x *TransactionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMetadata.ProtoReflect.Descriptor instead.
func (*TransactionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionMetadata) GetTotalQueries() int32 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *TransactionMetadata) GetSuccessfulQueries() int32 {
	if x != nil {
		return x.SuccessfulQueries
	}
	return 0
}

func (x *TransactionMetadata) GetTotalExecutionTimeMs() int32 {
	if x != nil {
		return x.TotalExecutionTimeMs
	}
	return 0
}

func (x *TransactionMetadata) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

// Graph Statistics
type GetGraphStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraphName     string                 `protobuf:"bytes,1,opt,name=graph_name,json=graphName,proto3" json:"graph_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphStatsRequest) Reset() {
	*x = GetGraphStatsRequest{}
	mi := &file_proto_graphops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphStatsRequest) ProtoMessage() {}

func (x *GetGraphStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGraphStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{10}
}

func (x *GetGraphStatsRequest) GetGraphName() string {
	if x != nil {
		return x.GraphName
	}
	return ""
}

type GetGraphStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *GraphStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphStatsResponse) Reset() {
	*x = GetGraphStatsResponse{}
	mi := &file_proto_graphops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphStatsResponse) ProtoMessage() {}

func (x *GetGraphStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGraphStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{11}
}

func (x *GetGraphStatsResponse) GetStats() *GraphStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GraphStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeCount     int64                  `protobuf:"varint,1,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount     int64                  `protobuf:"varint,2,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	NodeLabels    []*LabelStats          `protobuf:"bytes,3,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty"`
	EdgeLabels    []*LabelStats          `protobuf:"bytes,4,rep,name=edge_labels,json=edgeLabels,proto3" json:"edge_labels,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphStats) Reset() {
	*x = GraphStats{}
	mi := &file_proto_graphops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStats) ProtoMessage() {}

func (x *GraphStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStats.ProtoReflect.Descriptor instead.
func (*GraphStats) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{12}
}

func (x *GraphStats) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GraphStats) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GraphStats) GetNodeLabels() []*LabelStats {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

func (x *GraphStats) GetEdgeLabels() []*LabelStats {
	if x != nil {
		return x.EdgeLabels
	}
	return nil
}

func (x *GraphStats) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type LabelStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelStats) Reset() {
	*x = LabelStats{}
	mi := &file_proto_graphops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelStats) ProtoMessage() {}

func (x *LabelStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelStats.ProtoReflect.Descriptor instead.
func (*LabelStats) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{13}
}

func (x *LabelStats) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelStats) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_graphops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Database      *ConnectionStatus      `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_graphops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetDatabase() *ConnectionStatus {
	if x != nil {
		return x.Database
	}
	return nil
}

type ConnectionStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Connected         bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	IdleConnections   int32                  `protobuf:"varint,3,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	MaxConnections    int32                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_proto_graphops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graphops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_proto_graphops_proto_rawDescGZIP(), []int{16}
}

func (x *ConnectionStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectionStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ConnectionStatus) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *ConnectionStatus) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

var File_proto_graphops_proto protoreflect.FileDescriptor

const file_proto_graphops_proto_rawDesc = "" +
	"\n" +
	"\x14proto/graphops.proto\x12\x19ninaivalaigal.graphops.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x02\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12^\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2>.ninaivalaigal.graphops.v1.ExecuteQueryRequest.ParametersEntryR\n" +
	"parameters\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x14ExecuteQueryResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.ninaivalaigal.graphops.v1.QueryResultR\aresults\x12D\n" +
	"\bmetadata\x18\x02 \x01(\v2(.ninaivalaigal.graphops.v1.QueryMetadataR\bmetadata\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x88\x01\n" +
	"\vQueryResult\x12@\n" +
	"\acolumns\x18\x01 \x03(\v2&.ninaivalaigal.graphops.v1.QueryColumnR\acolumns\x127\n" +
	"\x04rows\x18\x02 \x03(\v2#.ninaivalaigal.graphops.v1.QueryRowR\x04rows\"5\n" +
	"\vQueryColumn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"I\n" +
	"\bQueryRow\x12=\n" +
	"\x06values\x18\x01 \x03(\v2%.ninaivalaigal.graphops.v1.QueryValueR\x06values\"\xc0\x01\n" +
	"\n" +
	"QueryValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x05 \x01(\fH\x00R\tjsonValueB\a\n" +
	"\x05value\"\x9b\x01\n" +
	"\rQueryMetadata\x12#\n" +
	"\rrows_affected\x18\x01 \x01(\x05R\frowsAffected\x12*\n" +
	"\x11execution_time_ms\x18\x02 \x01(\x05R\x0fexecutionTimeMs\x12\x1d\n" +
	"\n" +
	"query_plan\x18\x03 \x01(\tR\tqueryPlan\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"\x92\x02\n" +
	"\x19ExecuteTransactionRequest\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\x12d\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2D.ninaivalaigal.graphops.v1.ExecuteTransactionRequest.ParametersEntryR\n" +
	"parameters\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\x1aExecuteTransactionResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.ninaivalaigal.graphops.v1.QueryResultR\aresults\x12J\n" +
	"\bmetadata\x18\x02 \x01(\v2..ninaivalaigal.graphops.v1.TransactionMetadataR\bmetadata\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xbe\x01\n" +
	"\x13TransactionMetadata\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x05R\ftotalQueries\x12-\n" +
	"\x12successful_queries\x18\x02 \x01(\x05R\x11successfulQueries\x125\n" +
	"\x17total_execution_time_ms\x18\x03 \x01(\x05R\x14totalExecutionTimeMs\x12\x1c\n" +
	"\tcommitted\x18\x04 \x01(\bR\tcommitted\"5\n" +
	"\x14GetGraphStatsRequest\x12\x1d\n" +
	"\n" +
	"graph_name\x18\x01 \x01(\tR\tgraphName\"T\n" +
	"\x15GetGraphStatsResponse\x12;\n" +
	"\x05stats\x18\x01 \x01(\v2%.ninaivalaigal.graphops.v1.GraphStatsR\x05stats\"\x99\x02\n" +
	"\n" +
	"GraphStats\x12\x1d\n" +
	"\n" +
	"node_count\x18\x01 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x02 \x01(\x03R\tedgeCount\x12F\n" +
	"\vnode_labels\x18\x03 \x03(\v2%.ninaivalaigal.graphops.v1.LabelStatsR\n" +
	"nodeLabels\x12F\n" +
	"\vedge_labels\x18\x04 \x03(\v2%.ninaivalaigal.graphops.v1.LabelStatsR\n" +
	"edgeLabels\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"8\n" +
	"\n" +
	"LabelStats\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x14\n" +
	"\x12HealthCheckRequest\"\xca\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\bdatabase\x18\x04 \x01(\v2+.ninaivalaigal.graphops.v1.ConnectionStatusR\bdatabase\"\xb3\x01\n" +
	"\x10ConnectionStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10idle_connections\x18\x03 \x01(\x05R\x0fidleConnections\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05R\x0emaxConnections2\xe8\x03\n" +
	"\x0fGraphOpsService\x12o\n" +
	"\fExecuteQuery\x12..ninaivalaigal.graphops.v1.ExecuteQueryRequest\x1a/.ninaivalaigal.graphops.v1.ExecuteQueryResponse\x12\x81\x01\n" +
	"\x12ExecuteTransaction\x124.ninaivalaigal.graphops.v1.ExecuteTransactionRequest\x1a5.ninaivalaigal.graphops.v1.ExecuteTransactionResponse\x12l\n" +
	"\vHealthCheck\x12-.ninaivalaigal.graphops.v1.HealthCheckRequest\x1a..ninaivalaigal.graphops.v1.HealthCheckResponse\x12r\n" +
	"\rGetGraphStats\x12/.ninaivalaigal.graphops.v1.GetGraphStatsRequest\x1a0.ninaivalaigal.graphops.v1.GetGraphStatsResponseBBZ@github.com/arunosaur/ninaivalaigal/grpc-gateway/proto/graphopspbb\x06proto3"

var (
	file_proto_graphops_proto_rawDescOnce sync.Once
	file_proto_graphops_proto_rawDescData []byte
)

func file_proto_graphops_proto_rawDescGZIP() []byte {
	file_proto_graphops_proto_rawDescOnce.Do(func() {
		file_proto_graphops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graphops_proto_rawDesc), len(file_proto_graphops_proto_rawDesc)))
	})
	return file_proto_graphops_proto_rawDescData
}

var file_proto_graphops_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_graphops_proto_goTypes = []any{
	(*ExecuteQueryRequest)(nil),        // 0: ninaivalaigal.graphops.v1.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil),       // 1: ninaivalaigal.graphops.v1.ExecuteQueryResponse
	(*QueryResult)(nil),                // 2: ninaivalaigal.graphops.v1.QueryResult
	(*QueryColumn)(nil),                // 3: ninaivalaigal.graphops.v1.QueryColumn
	(*QueryRow)(nil),                   // 4: ninaivalaigal.graphops.v1.QueryRow
	(*QueryValue)(nil),                 // 5: ninaivalaigal.graphops.v1.QueryValue
	(*QueryMetadata)(nil),              // 6: ninaivalaigal.graphops.v1.QueryMetadata
	(*ExecuteTransactionRequest)(nil),  // 7: ninaivalaigal.graphops.v1.ExecuteTransactionRequest
	(*ExecuteTransactionResponse)(nil), // 8: ninaivalaigal.graphops.v1.ExecuteTransactionResponse
	(*TransactionMetadata)(nil),        // 9: ninaivalaigal.graphops.v1.TransactionMetadata
	(*GetGraphStatsRequest)(nil),       // 10: ninaivalaigal.graphops.v1.GetGraphStatsRequest
	(*GetGraphStatsResponse)(nil),      // 11: ninaivalaigal.graphops.v1.GetGraphStatsResponse
	(*GraphStats)(nil),                 // 12: ninaivalaigal.graphops.v1.GraphStats
	(*LabelStats)(nil),                 // 13: ninaivalaigal.graphops.v1.LabelStats
	(*HealthCheckRequest)(nil),         // 14: ninaivalaigal.graphops.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 15: ninaivalaigal.graphops.v1.HealthCheckResponse
	(*ConnectionStatus)(nil),           // 16: ninaivalaigal.graphops.v1.ConnectionStatus
	nil,                                // 17: ninaivalaigal.graphops.v1.ExecuteQueryRequest.ParametersEntry
	nil,                                // 18: ninaivalaigal.graphops.v1.ExecuteTransactionRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_proto_graphops_proto_depIdxs = []int32{
	17, // 0: ninaivalaigal.graphops.v1.ExecuteQueryRequest.parameters:type_name -> ninaivalaigal.graphops.v1.ExecuteQueryRequest.ParametersEntry
	2,  // 1: ninaivalaigal.graphops.v1.ExecuteQueryResponse.results:type_name -> ninaivalaigal.graphops.v1.QueryResult
	6,  // 2: ninaivalaigal.graphops.v1.ExecuteQueryResponse.metadata:type_name -> ninaivalaigal.graphops.v1.QueryMetadata
	3,  // 3: ninaivalaigal.graphops.v1.QueryResult.columns:type_name -> ninaivalaigal.graphops.v1.QueryColumn
	4,  // 4: ninaivalaigal.graphops.v1.QueryResult.rows:type_name -> ninaivalaigal.graphops.v1.QueryRow
	5,  // 5: ninaivalaigal.graphops.v1.QueryRow.values:type_name -> ninaivalaigal.graphops.v1.QueryValue
	18, // 6: ninaivalaigal.graphops.v1.ExecuteTransactionRequest.parameters:type_name -> ninaivalaigal.graphops.v1.ExecuteTransactionRequest.ParametersEntry
	2,  // 7: ninaivalaigal.graphops.v1.ExecuteTransactionResponse.results:type_name -> ninaivalaigal.graphops.v1.QueryResult
	9,  // 8: ninaivalaigal.graphops.v1.ExecuteTransactionResponse.metadata:type_name -> ninaivalaigal.graphops.v1.TransactionMetadata
	12, // 9: ninaivalaigal.graphops.v1.GetGraphStatsResponse.stats:type_name -> ninaivalaigal.graphops.v1.GraphStats
	13, // 10: ninaivalaigal.graphops.v1.GraphStats.node_labels:type_name -> ninaivalaigal.graphops.v1.LabelStats
	13, // 11: ninaivalaigal.graphops.v1.GraphStats.edge_labels:type_name -> ninaivalaigal.graphops.v1.LabelStats
	19, // 12: ninaivalaigal.graphops.v1.GraphStats.last_updated:type_name -> google.protobuf.Timestamp
	19, // 13: ninaivalaigal.graphops.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	16, // 14: ninaivalaigal.graphops.v1.HealthCheckResponse.database:type_name -> ninaivalaigal.graphops.v1.ConnectionStatus
	0,  // 15: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQuery:input_type -> ninaivalaigal.graphops.v1.ExecuteQueryRequest
	7,  // 16: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteTransaction:input_type -> ninaivalaigal.graphops.v1.ExecuteTransactionRequest
	14, // 17: ninaivalaigal.graphops.v1.GraphOpsService.HealthCheck:input_type -> ninaivalaigal.graphops.v1.HealthCheckRequest
	10, // 18: ninaivalaigal.graphops.v1.GraphOpsService.GetGraphStats:input_type -> ninaivalaigal.graphops.v1.GetGraphStatsRequest
	1,  // 19: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQuery:output_type -> ninaivalaigal.graphops.v1.ExecuteQueryResponse
	8,  // 20: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteTransaction:output_type -> ninaivalaigal.graphops.v1.ExecuteTransactionResponse
	15, // 21: ninaivalaigal.graphops.v1.GraphOpsService.HealthCheck:output_type -> ninaivalaigal.graphops.v1.HealthCheckResponse
	11, // 22: ninaivalaigal.graphops.v1.GraphOpsService.GetGraphStats:output_type -> ninaivalaigal.graphops.v1.GetGraphStatsResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_graphops_proto_init() }
func file_proto_graphops_proto_init() {
	if File_proto_graphops_proto != nil {
		return
	}
	file_proto_graphops_proto_msgTypes[5].OneofWrappers = []any{
		(*QueryValue_StringValue)(nil),
		(*QueryValue_IntValue)(nil),
		(*QueryValue_DoubleValue)(nil),
		(*QueryValue_BoolValue)(nil),
		(*QueryValue_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graphops_proto_rawDesc), len(file_proto_graphops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_graphops_proto_goTypes,
		DependencyIndexes: file_proto_graphops_proto_depIdxs,
		MessageInfos:      file_proto_graphops_proto_msgTypes,
	}.Build()
	File_proto_graphops_proto = out.File
	file_proto_graphops_proto_goTypes = nil
	file_proto_graphops_proto_depIdxs = nil
}
