# SPDX-License-Identifier: Proprietary
# Copyright (c) 2025 Medhasys LLC
#
# This file contains proprietary code owned by Medhasys LLC.
# Unauthorized copying, modification, or distribution is prohibited.
# See LICENSE file in the server/ directory for details.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ninaivalaigal-api-serviceaccount
  namespace: ninaivalaigal
  labels:
    app: ninaivalaigal-api
    component: backend
automountServiceAccountToken: true
