#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Medhasys LLC
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/errors.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "common/v1/errors.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63ommon/v1/errors.proto\x12\tcommon.v1"\xad\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x1d.common.v1.Error.DetailsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"?\n\x0fValidationError\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t">\n\x10ValidationErrors\x12*\n\x06\x65rrors\x18\x01 \x03(\x0b\x32\x1a.common.v1.ValidationError*\x89\x02\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x45RROR_CODE_INVALID_INPUT\x10\x01\x12\x18\n\x14\x45RROR_CODE_NOT_FOUND\x10\x02\x12\x1b\n\x17\x45RROR_CODE_UNAUTHORIZED\x10\x03\x12\x18\n\x14\x45RROR_CODE_FORBIDDEN\x10\x04\x12\x17\n\x13\x45RROR_CODE_CONFLICT\x10\x05\x12\x17\n\x13\x45RROR_CODE_INTERNAL\x10\x06\x12"\n\x1e\x45RROR_CODE_SERVICE_UNAVAILABLE\x10\x07\x12\x1b\n\x17\x45RROR_CODE_RATE_LIMITED\x10\x08\x42HZFgithub.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1;commonv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common.v1.errors_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"ZFgithub.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1;commonv1"
    )
    _globals["_ERROR_DETAILSENTRY"]._loaded_options = None
    _globals["_ERROR_DETAILSENTRY"]._serialized_options = b"8\001"
    _globals["_ERRORCODE"]._serialized_start = 343
    _globals["_ERRORCODE"]._serialized_end = 608
    _globals["_ERROR"]._serialized_start = 38
    _globals["_ERROR"]._serialized_end = 211
    _globals["_ERROR_DETAILSENTRY"]._serialized_start = 165
    _globals["_ERROR_DETAILSENTRY"]._serialized_end = 211
    _globals["_VALIDATIONERROR"]._serialized_start = 213
    _globals["_VALIDATIONERROR"]._serialized_end = 276
    _globals["_VALIDATIONERRORS"]._serialized_start = 278
    _globals["_VALIDATIONERRORS"]._serialized_end = 340
# @@protoc_insertion_point(module_scope)
