// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Medhasys LLC
//
// Common error types for all services

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common/v1/errors.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common error codes enum
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_INPUT       ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND           ErrorCode = 2
	ErrorCode_ERROR_CODE_UNAUTHORIZED        ErrorCode = 3
	ErrorCode_ERROR_CODE_FORBIDDEN           ErrorCode = 4
	ErrorCode_ERROR_CODE_CONFLICT            ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 6
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE ErrorCode = 7
	ErrorCode_ERROR_CODE_RATE_LIMITED        ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_INPUT",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_UNAUTHORIZED",
		4: "ERROR_CODE_FORBIDDEN",
		5: "ERROR_CODE_CONFLICT",
		6: "ERROR_CODE_INTERNAL",
		7: "ERROR_CODE_SERVICE_UNAVAILABLE",
		8: "ERROR_CODE_RATE_LIMITED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_INVALID_INPUT":       1,
		"ERROR_CODE_NOT_FOUND":           2,
		"ERROR_CODE_UNAUTHORIZED":        3,
		"ERROR_CODE_FORBIDDEN":           4,
		"ERROR_CODE_CONFLICT":            5,
		"ERROR_CODE_INTERNAL":            6,
		"ERROR_CODE_SERVICE_UNAVAILABLE": 7,
		"ERROR_CODE_RATE_LIMITED":        8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

// Standard error response
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code (e.g., "INVALID_INPUT", "NOT_FOUND")
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Additional error details
	Details map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp when error occurred
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Request ID for tracing
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Error) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Validation error for field-level issues
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field that failed validation
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Validation error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Error code specific to validation
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_common_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Error response with multiple validation errors
type ValidationErrors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ValidationError     `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationErrors) Reset() {
	*x = ValidationErrors{}
	mi := &file_common_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationErrors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationErrors) ProtoMessage() {}

func (x *ValidationErrors) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationErrors.ProtoReflect.Descriptor instead.
func (*ValidationErrors) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationErrors) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_common_v1_errors_proto protoreflect.FileDescriptor

const file_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/errors.proto\x12\tcommon.v1\"\xe7\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\adetails\x18\x03 \x03(\v2\x1d.common.v1.Error.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"F\n" +
	"\x10ValidationErrors\x122\n" +
	"\x06errors\x18\x01 \x03(\v2\x1a.common.v1.ValidationErrorR\x06errors*\x89\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x06\x12\"\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\a\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\bBHZFgithub.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_errors_proto_rawDescOnce sync.Once
	file_common_v1_errors_proto_rawDescData []byte
)

func file_common_v1_errors_proto_rawDescGZIP() []byte {
	file_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)))
	})
	return file_common_v1_errors_proto_rawDescData
}

var file_common_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),           // 0: common.v1.ErrorCode
	(*Error)(nil),            // 1: common.v1.Error
	(*ValidationError)(nil),  // 2: common.v1.ValidationError
	(*ValidationErrors)(nil), // 3: common.v1.ValidationErrors
	nil,                      // 4: common.v1.Error.DetailsEntry
}
var file_common_v1_errors_proto_depIdxs = []int32{
	4, // 0: common.v1.Error.details:type_name -> common.v1.Error.DetailsEntry
	2, // 1: common.v1.ValidationErrors.errors:type_name -> common.v1.ValidationError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_errors_proto_init() }
func file_common_v1_errors_proto_init() {
	if File_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_common_v1_errors_proto_depIdxs,
		EnumInfos:         file_common_v1_errors_proto_enumTypes,
		MessageInfos:      file_common_v1_errors_proto_msgTypes,
	}.Build()
	File_common_v1_errors_proto = out.File
	file_common_v1_errors_proto_goTypes = nil
	file_common_v1_errors_proto_depIdxs = nil
}
