# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/pagination.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/v1/pagination.proto\x12\tcommon.v1\"S\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0f\n\x07sort_by\x18\x03 \x01(\t\x12\x12\n\nsort_order\x18\x04 \x01(\t\"y\n\x08PageInfo\x12\r\n\x05total\x18\x01 \x01(\x05\x12\r\n\x05pages\x18\x02 \x01(\x05\x12\x14\n\x0c\x63urrent_page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x10\n\x08has_next\x18\x05 \x01(\x08\x12\x14\n\x0chas_previous\x18\x06 \x01(\x08\".\n\rCursorRequest\x12\x0e\n\x06\x63ursor\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"L\n\nCursorInfo\x12\x13\n\x0bnext_cursor\x18\x01 \x01(\t\x12\x17\n\x0fprevious_cursor\x18\x02 \x01(\t\x12\x10\n\x08has_more\x18\x03 \x01(\x08\x42HZFgithub.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1;commonv1'
  _globals['_PAGEREQUEST']._serialized_start=41
  _globals['_PAGEREQUEST']._serialized_end=124
  _globals['_PAGEINFO']._serialized_start=126
  _globals['_PAGEINFO']._serialized_end=247
  _globals['_CURSORREQUEST']._serialized_start=249
  _globals['_CURSORREQUEST']._serialized_end=295
  _globals['_CURSORINFO']._serialized_start=297
  _globals['_CURSORINFO']._serialized_end=373
# @@protoc_insertion_point(module_scope)
