#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Medhasys LLC
#
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "auth/v1/auth.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import errors_pb2 as common_dot_v1_dot_errors__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61uth/v1/auth.proto\x12\x07\x61uth.v1\x1a\x16\x63ommon/v1/errors.proto"\xb0\x01\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x38\n\x08metadata\x18\x04 \x03(\x0b\x32&.auth.v1.RegisterRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"\'\n\x0fValidateRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t"%\n\rLogoutRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t"\x80\x01\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x03\x12\x12\n\ntoken_type\x18\x04 \x01(\t\x12\x1b\n\x04user\x18\x05 \x01(\x0b\x32\r.auth.v1.User"b\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x1b\n\x04user\x18\x02 \x01(\x0b\x32\r.auth.v1.User\x12\r\n\x05roles\x18\x03 \x03(\t\x12\x13\n\x0bpermissions\x18\x04 \x03(\t"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"j\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\r\n\x05roles\x18\x04 \x03(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t2\xc2\x02\n\x0b\x41uthService\x12;\n\x08Register\x12\x18.auth.v1.RegisterRequest\x1a\x15.auth.v1.AuthResponse\x12\x35\n\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x15.auth.v1.AuthResponse\x12>\n\x0cRefreshToken\x12\x17.auth.v1.RefreshRequest\x1a\x15.auth.v1.AuthResponse\x12\x44\n\rValidateToken\x12\x18.auth.v1.ValidateRequest\x1a\x19.auth.v1.ValidateResponse\x12\x39\n\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x17.auth.v1.LogoutResponseBDZBgithub.com/Arunosaur/ninaivalaigal/shared/contracts/auth/v1;authv1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "auth.v1.auth_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"ZBgithub.com/Arunosaur/ninaivalaigal/shared/contracts/auth/v1;authv1"
    _globals["_REGISTERREQUEST_METADATAENTRY"]._loaded_options = None
    _globals["_REGISTERREQUEST_METADATAENTRY"]._serialized_options = b"8\001"
    _globals["_REGISTERREQUEST"]._serialized_start = 56
    _globals["_REGISTERREQUEST"]._serialized_end = 232
    _globals["_REGISTERREQUEST_METADATAENTRY"]._serialized_start = 185
    _globals["_REGISTERREQUEST_METADATAENTRY"]._serialized_end = 232
    _globals["_LOGINREQUEST"]._serialized_start = 234
    _globals["_LOGINREQUEST"]._serialized_end = 281
    _globals["_REFRESHREQUEST"]._serialized_start = 283
    _globals["_REFRESHREQUEST"]._serialized_end = 322
    _globals["_VALIDATEREQUEST"]._serialized_start = 324
    _globals["_VALIDATEREQUEST"]._serialized_end = 363
    _globals["_LOGOUTREQUEST"]._serialized_start = 365
    _globals["_LOGOUTREQUEST"]._serialized_end = 402
    _globals["_AUTHRESPONSE"]._serialized_start = 405
    _globals["_AUTHRESPONSE"]._serialized_end = 533
    _globals["_VALIDATERESPONSE"]._serialized_start = 535
    _globals["_VALIDATERESPONSE"]._serialized_end = 633
    _globals["_LOGOUTRESPONSE"]._serialized_start = 635
    _globals["_LOGOUTRESPONSE"]._serialized_end = 668
    _globals["_USER"]._serialized_start = 670
    _globals["_USER"]._serialized_end = 776
    _globals["_AUTHSERVICE"]._serialized_start = 779
    _globals["_AUTHSERVICE"]._serialized_end = 1101
# @@protoc_insertion_point(module_scope)
