#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Medhasys LLC
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from memory.v1 import memory_pb2 as memory_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in memory/v1/memory_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MemoryServiceStub(object):
    """Memory Service - gRPC definitions"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Remember = channel.unary_unary(
            "/ninaivalaigal.memory.v1.MemoryService/Remember",
            request_serializer=memory_dot_v1_dot_memory__pb2.RememberRequest.SerializeToString,
            response_deserializer=memory_dot_v1_dot_memory__pb2.RememberResponse.FromString,
            _registered_method=True,
        )
        self.Recall = channel.unary_unary(
            "/ninaivalaigal.memory.v1.MemoryService/Recall",
            request_serializer=memory_dot_v1_dot_memory__pb2.RecallRequest.SerializeToString,
            response_deserializer=memory_dot_v1_dot_memory__pb2.RecallResponse.FromString,
            _registered_method=True,
        )
        self.ListMemories = channel.unary_unary(
            "/ninaivalaigal.memory.v1.MemoryService/ListMemories",
            request_serializer=memory_dot_v1_dot_memory__pb2.ListMemoriesRequest.SerializeToString,
            response_deserializer=memory_dot_v1_dot_memory__pb2.ListMemoriesResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/ninaivalaigal.memory.v1.MemoryService/HealthCheck",
            request_serializer=memory_dot_v1_dot_memory__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=memory_dot_v1_dot_memory__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class MemoryServiceServicer(object):
    """Memory Service - gRPC definitions"""

    def Remember(self, request, context):
        """Store a new memory"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Recall(self, request, context):
        """Recall memories based on query"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMemories(self, request, context):
        """List all memories for a user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Remember": grpc.unary_unary_rpc_method_handler(
            servicer.Remember,
            request_deserializer=memory_dot_v1_dot_memory__pb2.RememberRequest.FromString,
            response_serializer=memory_dot_v1_dot_memory__pb2.RememberResponse.SerializeToString,
        ),
        "Recall": grpc.unary_unary_rpc_method_handler(
            servicer.Recall,
            request_deserializer=memory_dot_v1_dot_memory__pb2.RecallRequest.FromString,
            response_serializer=memory_dot_v1_dot_memory__pb2.RecallResponse.SerializeToString,
        ),
        "ListMemories": grpc.unary_unary_rpc_method_handler(
            servicer.ListMemories,
            request_deserializer=memory_dot_v1_dot_memory__pb2.ListMemoriesRequest.FromString,
            response_serializer=memory_dot_v1_dot_memory__pb2.ListMemoriesResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=memory_dot_v1_dot_memory__pb2.HealthCheckRequest.FromString,
            response_serializer=memory_dot_v1_dot_memory__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ninaivalaigal.memory.v1.MemoryService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ninaivalaigal.memory.v1.MemoryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """Memory Service - gRPC definitions"""

    @staticmethod
    def Remember(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ninaivalaigal.memory.v1.MemoryService/Remember",
            memory_dot_v1_dot_memory__pb2.RememberRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Recall(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ninaivalaigal.memory.v1.MemoryService/Recall",
            memory_dot_v1_dot_memory__pb2.RecallRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMemories(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ninaivalaigal.memory.v1.MemoryService/ListMemories",
            memory_dot_v1_dot_memory__pb2.ListMemoriesRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.ListMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ninaivalaigal.memory.v1.MemoryService/HealthCheck",
            memory_dot_v1_dot_memory__pb2.HealthCheckRequest.SerializeToString,
            memory_dot_v1_dot_memory__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
