// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: memory/v1/memory.proto

package memorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Remember (Store Memory)
type RememberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberRequest) Reset() {
	*x = RememberRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberRequest) ProtoMessage() {}

func (x *RememberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberRequest.ProtoReflect.Descriptor instead.
func (*RememberRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *RememberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RememberRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RememberRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *RememberRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RememberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberResponse) Reset() {
	*x = RememberResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberResponse) ProtoMessage() {}

func (x *RememberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberResponse.ProtoReflect.Descriptor instead.
func (*RememberResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *RememberResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *RememberResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RememberResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Recall (Retrieve Memories)
type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Threshold     float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"` // similarity threshold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *RecallRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecallRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*Memory              `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RecallResponse) GetMemories() []*Memory {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *RecallResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// List Memories
type ListMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesRequest) Reset() {
	*x = ListMemoriesRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesRequest) ProtoMessage() {}

func (x *ListMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *ListMemoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMemoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMemoriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*Memory              `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesResponse) Reset() {
	*x = ListMemoriesResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesResponse) ProtoMessage() {}

func (x *ListMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *ListMemoriesResponse) GetMemories() []*Memory {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *ListMemoriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMemoriesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMemoriesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Memory object
type Memory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Context        string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,8,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"` // for recall operations
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *Memory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Memory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memory) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Memory) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Memory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Memory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Memory) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_memory_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_memory_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_memory_v1_memory_proto protoreflect.FileDescriptor

const file_memory_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x16memory/v1/memory.proto\x12\x17ninaivalaigal.memory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\x0fRememberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.ninaivalaigal.memory.v1.RememberRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x10RememberResponse\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"r\n" +
	"\rRecallRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\"n\n" +
	"\x0eRecallResponse\x12;\n" +
	"\bmemories\x18\x01 \x03(\v2\x1f.ninaivalaigal.memory.v1.MemoryR\bmemories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"_\n" +
	"\x13ListMemoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xa5\x01\n" +
	"\x14ListMemoriesResponse\x12;\n" +
	"\bmemories\x18\x01 \x03(\v2\x1f.ninaivalaigal.memory.v1.MemoryR\bmemories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8c\x03\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.ninaivalaigal.memory.v1.Memory.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0frelevance_score\x18\b \x01(\x02R\x0erelevanceScore\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"\x81\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xa2\x03\n" +
	"\rMemoryService\x12_\n" +
	"\bRemember\x12(.ninaivalaigal.memory.v1.RememberRequest\x1a).ninaivalaigal.memory.v1.RememberResponse\x12Y\n" +
	"\x06Recall\x12&.ninaivalaigal.memory.v1.RecallRequest\x1a'.ninaivalaigal.memory.v1.RecallResponse\x12k\n" +
	"\fListMemories\x12,.ninaivalaigal.memory.v1.ListMemoriesRequest\x1a-.ninaivalaigal.memory.v1.ListMemoriesResponse\x12h\n" +
	"\vHealthCheck\x12+.ninaivalaigal.memory.v1.HealthCheckRequest\x1a,.ninaivalaigal.memory.v1.HealthCheckResponseB@Z>github.com/arunosaur/ninaivalaigal/grpc-gateway/proto/memorypbb\x06proto3"

var (
	file_memory_v1_memory_proto_rawDescOnce sync.Once
	file_memory_v1_memory_proto_rawDescData []byte
)

func file_memory_v1_memory_proto_rawDescGZIP() []byte {
	file_memory_v1_memory_proto_rawDescOnce.Do(func() {
		file_memory_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)))
	})
	return file_memory_v1_memory_proto_rawDescData
}

var file_memory_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_memory_v1_memory_proto_goTypes = []any{
	(*RememberRequest)(nil),       // 0: ninaivalaigal.memory.v1.RememberRequest
	(*RememberResponse)(nil),      // 1: ninaivalaigal.memory.v1.RememberResponse
	(*RecallRequest)(nil),         // 2: ninaivalaigal.memory.v1.RecallRequest
	(*RecallResponse)(nil),        // 3: ninaivalaigal.memory.v1.RecallResponse
	(*ListMemoriesRequest)(nil),   // 4: ninaivalaigal.memory.v1.ListMemoriesRequest
	(*ListMemoriesResponse)(nil),  // 5: ninaivalaigal.memory.v1.ListMemoriesResponse
	(*Memory)(nil),                // 6: ninaivalaigal.memory.v1.Memory
	(*HealthCheckRequest)(nil),    // 7: ninaivalaigal.memory.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: ninaivalaigal.memory.v1.HealthCheckResponse
	nil,                           // 9: ninaivalaigal.memory.v1.RememberRequest.MetadataEntry
	nil,                           // 10: ninaivalaigal.memory.v1.Memory.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_memory_v1_memory_proto_depIdxs = []int32{
	9,  // 0: ninaivalaigal.memory.v1.RememberRequest.metadata:type_name -> ninaivalaigal.memory.v1.RememberRequest.MetadataEntry
	11, // 1: ninaivalaigal.memory.v1.RememberResponse.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: ninaivalaigal.memory.v1.RecallResponse.memories:type_name -> ninaivalaigal.memory.v1.Memory
	6,  // 3: ninaivalaigal.memory.v1.ListMemoriesResponse.memories:type_name -> ninaivalaigal.memory.v1.Memory
	10, // 4: ninaivalaigal.memory.v1.Memory.metadata:type_name -> ninaivalaigal.memory.v1.Memory.MetadataEntry
	11, // 5: ninaivalaigal.memory.v1.Memory.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: ninaivalaigal.memory.v1.Memory.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: ninaivalaigal.memory.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: ninaivalaigal.memory.v1.MemoryService.Remember:input_type -> ninaivalaigal.memory.v1.RememberRequest
	2,  // 9: ninaivalaigal.memory.v1.MemoryService.Recall:input_type -> ninaivalaigal.memory.v1.RecallRequest
	4,  // 10: ninaivalaigal.memory.v1.MemoryService.ListMemories:input_type -> ninaivalaigal.memory.v1.ListMemoriesRequest
	7,  // 11: ninaivalaigal.memory.v1.MemoryService.HealthCheck:input_type -> ninaivalaigal.memory.v1.HealthCheckRequest
	1,  // 12: ninaivalaigal.memory.v1.MemoryService.Remember:output_type -> ninaivalaigal.memory.v1.RememberResponse
	3,  // 13: ninaivalaigal.memory.v1.MemoryService.Recall:output_type -> ninaivalaigal.memory.v1.RecallResponse
	5,  // 14: ninaivalaigal.memory.v1.MemoryService.ListMemories:output_type -> ninaivalaigal.memory.v1.ListMemoriesResponse
	8,  // 15: ninaivalaigal.memory.v1.MemoryService.HealthCheck:output_type -> ninaivalaigal.memory.v1.HealthCheckResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_memory_v1_memory_proto_init() }
func file_memory_v1_memory_proto_init() {
	if File_memory_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_v1_memory_proto_rawDesc), len(file_memory_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_v1_memory_proto_goTypes,
		DependencyIndexes: file_memory_v1_memory_proto_depIdxs,
		MessageInfos:      file_memory_v1_memory_proto_msgTypes,
	}.Build()
	File_memory_v1_memory_proto = out.File
	file_memory_v1_memory_proto_goTypes = nil
	file_memory_v1_memory_proto_depIdxs = nil
}
