apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: ninaivalaigal
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>

---
# To generate this secret, run:
# kubectl create secret docker-registry ghcr-pull-secret \
#   --docker-server=ghcr.io \
#   --docker-username=Arunosaur \
#   --docker-password=$GHCR_PAT \
#   --docker-email=you@example.com \
#   --dry-run=client -o yaml
