# Makefile for Ninaivalaigal Unified Runtime
# SPEC-107: Unified Runtime Parity & Deployment Standard

dev:
	\tENV=dev docker compose up --build

test:
	\tENV=test docker compose up --build

prod:
	\tENV=prod docker compose up -d

stop:
	\tdocker compose down
