// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Medhasys LLC
//
// Analytics service contract

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: business/v1/analytics.proto

package businessv1

import (
	_ "github.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get user analytics request
type GetUserAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAnalyticsRequest) Reset() {
	*x = GetUserAnalyticsRequest{}
	mi := &file_business_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAnalyticsRequest) ProtoMessage() {}

func (x *GetUserAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAnalyticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAnalyticsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetUserAnalyticsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Get organization analytics request
type GetOrganizationAnalyticsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationAnalyticsRequest) Reset() {
	*x = GetOrganizationAnalyticsRequest{}
	mi := &file_business_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationAnalyticsRequest) ProtoMessage() {}

func (x *GetOrganizationAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrganizationAnalyticsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOrganizationAnalyticsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetOrganizationAnalyticsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Get engagement request
type GetEngagementRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Period         string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // daily, weekly, monthly
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEngagementRequest) Reset() {
	*x = GetEngagementRequest{}
	mi := &file_business_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngagementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngagementRequest) ProtoMessage() {}

func (x *GetEngagementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngagementRequest.ProtoReflect.Descriptor instead.
func (*GetEngagementRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetEngagementRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetEngagementRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// Get cohort request
type GetCohortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Grouping      string                 `protobuf:"bytes,3,opt,name=grouping,proto3" json:"grouping,omitempty"` // signup_month, tier, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCohortRequest) Reset() {
	*x = GetCohortRequest{}
	mi := &file_business_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCohortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCohortRequest) ProtoMessage() {}

func (x *GetCohortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCohortRequest.ProtoReflect.Descriptor instead.
func (*GetCohortRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetCohortRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetCohortRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetCohortRequest) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

// User analytics
type UserAnalytics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalMemories     int64                  `protobuf:"varint,2,opt,name=total_memories,json=totalMemories,proto3" json:"total_memories,omitempty"`
	TotalApiCalls     int64                  `protobuf:"varint,3,opt,name=total_api_calls,json=totalApiCalls,proto3" json:"total_api_calls,omitempty"`
	TotalStorageBytes int64                  `protobuf:"varint,4,opt,name=total_storage_bytes,json=totalStorageBytes,proto3" json:"total_storage_bytes,omitempty"`
	DailyMetrics      []*DailyMetric         `protobuf:"bytes,5,rep,name=daily_metrics,json=dailyMetrics,proto3" json:"daily_metrics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserAnalytics) Reset() {
	*x = UserAnalytics{}
	mi := &file_business_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnalytics) ProtoMessage() {}

func (x *UserAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnalytics.ProtoReflect.Descriptor instead.
func (*UserAnalytics) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *UserAnalytics) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAnalytics) GetTotalMemories() int64 {
	if x != nil {
		return x.TotalMemories
	}
	return 0
}

func (x *UserAnalytics) GetTotalApiCalls() int64 {
	if x != nil {
		return x.TotalApiCalls
	}
	return 0
}

func (x *UserAnalytics) GetTotalStorageBytes() int64 {
	if x != nil {
		return x.TotalStorageBytes
	}
	return 0
}

func (x *UserAnalytics) GetDailyMetrics() []*DailyMetric {
	if x != nil {
		return x.DailyMetrics
	}
	return nil
}

// Organization analytics
type OrganizationAnalytics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TotalUsers     int64                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers    int64                  `protobuf:"varint,3,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	TotalMemories  int64                  `protobuf:"varint,4,opt,name=total_memories,json=totalMemories,proto3" json:"total_memories,omitempty"`
	TotalApiCalls  int64                  `protobuf:"varint,5,opt,name=total_api_calls,json=totalApiCalls,proto3" json:"total_api_calls,omitempty"`
	TotalRevenue   float64                `protobuf:"fixed64,6,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TeamMetrics    []*TeamMetric          `protobuf:"bytes,7,rep,name=team_metrics,json=teamMetrics,proto3" json:"team_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationAnalytics) Reset() {
	*x = OrganizationAnalytics{}
	mi := &file_business_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationAnalytics) ProtoMessage() {}

func (x *OrganizationAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationAnalytics.ProtoReflect.Descriptor instead.
func (*OrganizationAnalytics) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationAnalytics) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationAnalytics) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *OrganizationAnalytics) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *OrganizationAnalytics) GetTotalMemories() int64 {
	if x != nil {
		return x.TotalMemories
	}
	return 0
}

func (x *OrganizationAnalytics) GetTotalApiCalls() int64 {
	if x != nil {
		return x.TotalApiCalls
	}
	return 0
}

func (x *OrganizationAnalytics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrganizationAnalytics) GetTeamMetrics() []*TeamMetric {
	if x != nil {
		return x.TeamMetrics
	}
	return nil
}

// Engagement metrics
type EngagementMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DailyActiveUsers   int64                  `protobuf:"varint,1,opt,name=daily_active_users,json=dailyActiveUsers,proto3" json:"daily_active_users,omitempty"`
	WeeklyActiveUsers  int64                  `protobuf:"varint,2,opt,name=weekly_active_users,json=weeklyActiveUsers,proto3" json:"weekly_active_users,omitempty"`
	MonthlyActiveUsers int64                  `protobuf:"varint,3,opt,name=monthly_active_users,json=monthlyActiveUsers,proto3" json:"monthly_active_users,omitempty"`
	RetentionRate      float64                `protobuf:"fixed64,4,opt,name=retention_rate,json=retentionRate,proto3" json:"retention_rate,omitempty"`
	ChurnRate          float64                `protobuf:"fixed64,5,opt,name=churn_rate,json=churnRate,proto3" json:"churn_rate,omitempty"`
	EngagementTimeline []*EngagementPoint     `protobuf:"bytes,6,rep,name=engagement_timeline,json=engagementTimeline,proto3" json:"engagement_timeline,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EngagementMetrics) Reset() {
	*x = EngagementMetrics{}
	mi := &file_business_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementMetrics) ProtoMessage() {}

func (x *EngagementMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementMetrics.ProtoReflect.Descriptor instead.
func (*EngagementMetrics) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *EngagementMetrics) GetDailyActiveUsers() int64 {
	if x != nil {
		return x.DailyActiveUsers
	}
	return 0
}

func (x *EngagementMetrics) GetWeeklyActiveUsers() int64 {
	if x != nil {
		return x.WeeklyActiveUsers
	}
	return 0
}

func (x *EngagementMetrics) GetMonthlyActiveUsers() int64 {
	if x != nil {
		return x.MonthlyActiveUsers
	}
	return 0
}

func (x *EngagementMetrics) GetRetentionRate() float64 {
	if x != nil {
		return x.RetentionRate
	}
	return 0
}

func (x *EngagementMetrics) GetChurnRate() float64 {
	if x != nil {
		return x.ChurnRate
	}
	return 0
}

func (x *EngagementMetrics) GetEngagementTimeline() []*EngagementPoint {
	if x != nil {
		return x.EngagementTimeline
	}
	return nil
}

// Cohort analysis
type CohortAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cohorts       []*CohortGroup         `protobuf:"bytes,1,rep,name=cohorts,proto3" json:"cohorts,omitempty"`
	Grouping      string                 `protobuf:"bytes,2,opt,name=grouping,proto3" json:"grouping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CohortAnalysis) Reset() {
	*x = CohortAnalysis{}
	mi := &file_business_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortAnalysis) ProtoMessage() {}

func (x *CohortAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortAnalysis.ProtoReflect.Descriptor instead.
func (*CohortAnalysis) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *CohortAnalysis) GetCohorts() []*CohortGroup {
	if x != nil {
		return x.Cohorts
	}
	return nil
}

func (x *CohortAnalysis) GetGrouping() string {
	if x != nil {
		return x.Grouping
	}
	return ""
}

// Daily metric
type DailyMetric struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ApiCalls        int64                  `protobuf:"varint,2,opt,name=api_calls,json=apiCalls,proto3" json:"api_calls,omitempty"`
	MemoriesCreated int64                  `protobuf:"varint,3,opt,name=memories_created,json=memoriesCreated,proto3" json:"memories_created,omitempty"`
	StorageUsed     int64                  `protobuf:"varint,4,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyMetric) Reset() {
	*x = DailyMetric{}
	mi := &file_business_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyMetric) ProtoMessage() {}

func (x *DailyMetric) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyMetric.ProtoReflect.Descriptor instead.
func (*DailyMetric) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *DailyMetric) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyMetric) GetApiCalls() int64 {
	if x != nil {
		return x.ApiCalls
	}
	return 0
}

func (x *DailyMetric) GetMemoriesCreated() int64 {
	if x != nil {
		return x.MemoriesCreated
	}
	return 0
}

func (x *DailyMetric) GetStorageUsed() int64 {
	if x != nil {
		return x.StorageUsed
	}
	return 0
}

// Team metric
type TeamMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName      string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Members       int64                  `protobuf:"varint,3,opt,name=members,proto3" json:"members,omitempty"`
	Memories      int64                  `protobuf:"varint,4,opt,name=memories,proto3" json:"memories,omitempty"`
	ApiCalls      int64                  `protobuf:"varint,5,opt,name=api_calls,json=apiCalls,proto3" json:"api_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMetric) Reset() {
	*x = TeamMetric{}
	mi := &file_business_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMetric) ProtoMessage() {}

func (x *TeamMetric) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMetric.ProtoReflect.Descriptor instead.
func (*TeamMetric) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TeamMetric) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamMetric) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TeamMetric) GetMembers() int64 {
	if x != nil {
		return x.Members
	}
	return 0
}

func (x *TeamMetric) GetMemories() int64 {
	if x != nil {
		return x.Memories
	}
	return 0
}

func (x *TeamMetric) GetApiCalls() int64 {
	if x != nil {
		return x.ApiCalls
	}
	return 0
}

// Engagement point
type EngagementPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ActiveUsers   int64                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	NewUsers      int64                  `protobuf:"varint,3,opt,name=new_users,json=newUsers,proto3" json:"new_users,omitempty"`
	ChurnedUsers  int64                  `protobuf:"varint,4,opt,name=churned_users,json=churnedUsers,proto3" json:"churned_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngagementPoint) Reset() {
	*x = EngagementPoint{}
	mi := &file_business_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementPoint) ProtoMessage() {}

func (x *EngagementPoint) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementPoint.ProtoReflect.Descriptor instead.
func (*EngagementPoint) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *EngagementPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EngagementPoint) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *EngagementPoint) GetNewUsers() int64 {
	if x != nil {
		return x.NewUsers
	}
	return 0
}

func (x *EngagementPoint) GetChurnedUsers() int64 {
	if x != nil {
		return x.ChurnedUsers
	}
	return 0
}

// Cohort group
type CohortGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CohortId       string                 `protobuf:"bytes,1,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	InitialUsers   int64                  `protobuf:"varint,3,opt,name=initial_users,json=initialUsers,proto3" json:"initial_users,omitempty"`
	RetentionRates []float64              `protobuf:"fixed64,4,rep,packed,name=retention_rates,json=retentionRates,proto3" json:"retention_rates,omitempty"` // retention at week 1, 2, 3, etc.
	LifetimeValue  float64                `protobuf:"fixed64,5,opt,name=lifetime_value,json=lifetimeValue,proto3" json:"lifetime_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CohortGroup) Reset() {
	*x = CohortGroup{}
	mi := &file_business_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortGroup) ProtoMessage() {}

func (x *CohortGroup) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortGroup.ProtoReflect.Descriptor instead.
func (*CohortGroup) Descriptor() ([]byte, []int) {
	return file_business_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *CohortGroup) GetCohortId() string {
	if x != nil {
		return x.CohortId
	}
	return ""
}

func (x *CohortGroup) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CohortGroup) GetInitialUsers() int64 {
	if x != nil {
		return x.InitialUsers
	}
	return 0
}

func (x *CohortGroup) GetRetentionRates() []float64 {
	if x != nil {
		return x.RetentionRates
	}
	return nil
}

func (x *CohortGroup) GetLifetimeValue() float64 {
	if x != nil {
		return x.LifetimeValue
	}
	return 0
}

var File_business_v1_analytics_proto protoreflect.FileDescriptor

const file_business_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1bbusiness/v1/analytics.proto\x12\vbusiness.v1\x1a\x1acommon/v1/pagination.proto\"l\n" +
	"\x17GetUserAnalyticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x84\x01\n" +
	"\x1fGetOrganizationAnalyticsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"W\n" +
	"\x14GetEngagementRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"h\n" +
	"\x10GetCohortRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x1a\n" +
	"\bgrouping\x18\x03 \x01(\tR\bgrouping\"\xe6\x01\n" +
	"\rUserAnalytics\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0etotal_memories\x18\x02 \x01(\x03R\rtotalMemories\x12&\n" +
	"\x0ftotal_api_calls\x18\x03 \x01(\x03R\rtotalApiCalls\x12.\n" +
	"\x13total_storage_bytes\x18\x04 \x01(\x03R\x11totalStorageBytes\x12=\n" +
	"\rdaily_metrics\x18\x05 \x03(\v2\x18.business.v1.DailyMetricR\fdailyMetrics\"\xb4\x02\n" +
	"\x15OrganizationAnalytics\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x03 \x01(\x03R\vactiveUsers\x12%\n" +
	"\x0etotal_memories\x18\x04 \x01(\x03R\rtotalMemories\x12&\n" +
	"\x0ftotal_api_calls\x18\x05 \x01(\x03R\rtotalApiCalls\x12#\n" +
	"\rtotal_revenue\x18\x06 \x01(\x01R\ftotalRevenue\x12:\n" +
	"\fteam_metrics\x18\a \x03(\v2\x17.business.v1.TeamMetricR\vteamMetrics\"\xb8\x02\n" +
	"\x11EngagementMetrics\x12,\n" +
	"\x12daily_active_users\x18\x01 \x01(\x03R\x10dailyActiveUsers\x12.\n" +
	"\x13weekly_active_users\x18\x02 \x01(\x03R\x11weeklyActiveUsers\x120\n" +
	"\x14monthly_active_users\x18\x03 \x01(\x03R\x12monthlyActiveUsers\x12%\n" +
	"\x0eretention_rate\x18\x04 \x01(\x01R\rretentionRate\x12\x1d\n" +
	"\n" +
	"churn_rate\x18\x05 \x01(\x01R\tchurnRate\x12M\n" +
	"\x13engagement_timeline\x18\x06 \x03(\v2\x1c.business.v1.EngagementPointR\x12engagementTimeline\"`\n" +
	"\x0eCohortAnalysis\x122\n" +
	"\acohorts\x18\x01 \x03(\v2\x18.business.v1.CohortGroupR\acohorts\x12\x1a\n" +
	"\bgrouping\x18\x02 \x01(\tR\bgrouping\"\x8c\x01\n" +
	"\vDailyMetric\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1b\n" +
	"\tapi_calls\x18\x02 \x01(\x03R\bapiCalls\x12)\n" +
	"\x10memories_created\x18\x03 \x01(\x03R\x0fmemoriesCreated\x12!\n" +
	"\fstorage_used\x18\x04 \x01(\x03R\vstorageUsed\"\x95\x01\n" +
	"\n" +
	"TeamMetric\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12\x18\n" +
	"\amembers\x18\x03 \x01(\x03R\amembers\x12\x1a\n" +
	"\bmemories\x18\x04 \x01(\x03R\bmemories\x12\x1b\n" +
	"\tapi_calls\x18\x05 \x01(\x03R\bapiCalls\"\x8a\x01\n" +
	"\x0fEngagementPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\factive_users\x18\x02 \x01(\x03R\vactiveUsers\x12\x1b\n" +
	"\tnew_users\x18\x03 \x01(\x03R\bnewUsers\x12#\n" +
	"\rchurned_users\x18\x04 \x01(\x03R\fchurnedUsers\"\xbe\x01\n" +
	"\vCohortGroup\x12\x1b\n" +
	"\tcohort_id\x18\x01 \x01(\tR\bcohortId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12#\n" +
	"\rinitial_users\x18\x03 \x01(\x03R\finitialUsers\x12'\n" +
	"\x0fretention_rates\x18\x04 \x03(\x01R\x0eretentionRates\x12%\n" +
	"\x0elifetime_value\x18\x05 \x01(\x01R\rlifetimeValue2\x82\x03\n" +
	"\x10AnalyticsService\x12T\n" +
	"\x10GetUserAnalytics\x12$.business.v1.GetUserAnalyticsRequest\x1a\x1a.business.v1.UserAnalytics\x12l\n" +
	"\x18GetOrganizationAnalytics\x12,.business.v1.GetOrganizationAnalyticsRequest\x1a\".business.v1.OrganizationAnalytics\x12Y\n" +
	"\x14GetEngagementMetrics\x12!.business.v1.GetEngagementRequest\x1a\x1e.business.v1.EngagementMetrics\x12O\n" +
	"\x11GetCohortAnalysis\x12\x1d.business.v1.GetCohortRequest\x1a\x1b.business.v1.CohortAnalysisBLZJgithub.com/Arunosaur/ninaivalaigal/shared/contracts/business/v1;businessv1b\x06proto3"

var (
	file_business_v1_analytics_proto_rawDescOnce sync.Once
	file_business_v1_analytics_proto_rawDescData []byte
)

func file_business_v1_analytics_proto_rawDescGZIP() []byte {
	file_business_v1_analytics_proto_rawDescOnce.Do(func() {
		file_business_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_v1_analytics_proto_rawDesc), len(file_business_v1_analytics_proto_rawDesc)))
	})
	return file_business_v1_analytics_proto_rawDescData
}

var file_business_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_business_v1_analytics_proto_goTypes = []any{
	(*GetUserAnalyticsRequest)(nil),         // 0: business.v1.GetUserAnalyticsRequest
	(*GetOrganizationAnalyticsRequest)(nil), // 1: business.v1.GetOrganizationAnalyticsRequest
	(*GetEngagementRequest)(nil),            // 2: business.v1.GetEngagementRequest
	(*GetCohortRequest)(nil),                // 3: business.v1.GetCohortRequest
	(*UserAnalytics)(nil),                   // 4: business.v1.UserAnalytics
	(*OrganizationAnalytics)(nil),           // 5: business.v1.OrganizationAnalytics
	(*EngagementMetrics)(nil),               // 6: business.v1.EngagementMetrics
	(*CohortAnalysis)(nil),                  // 7: business.v1.CohortAnalysis
	(*DailyMetric)(nil),                     // 8: business.v1.DailyMetric
	(*TeamMetric)(nil),                      // 9: business.v1.TeamMetric
	(*EngagementPoint)(nil),                 // 10: business.v1.EngagementPoint
	(*CohortGroup)(nil),                     // 11: business.v1.CohortGroup
}
var file_business_v1_analytics_proto_depIdxs = []int32{
	8,  // 0: business.v1.UserAnalytics.daily_metrics:type_name -> business.v1.DailyMetric
	9,  // 1: business.v1.OrganizationAnalytics.team_metrics:type_name -> business.v1.TeamMetric
	10, // 2: business.v1.EngagementMetrics.engagement_timeline:type_name -> business.v1.EngagementPoint
	11, // 3: business.v1.CohortAnalysis.cohorts:type_name -> business.v1.CohortGroup
	0,  // 4: business.v1.AnalyticsService.GetUserAnalytics:input_type -> business.v1.GetUserAnalyticsRequest
	1,  // 5: business.v1.AnalyticsService.GetOrganizationAnalytics:input_type -> business.v1.GetOrganizationAnalyticsRequest
	2,  // 6: business.v1.AnalyticsService.GetEngagementMetrics:input_type -> business.v1.GetEngagementRequest
	3,  // 7: business.v1.AnalyticsService.GetCohortAnalysis:input_type -> business.v1.GetCohortRequest
	4,  // 8: business.v1.AnalyticsService.GetUserAnalytics:output_type -> business.v1.UserAnalytics
	5,  // 9: business.v1.AnalyticsService.GetOrganizationAnalytics:output_type -> business.v1.OrganizationAnalytics
	6,  // 10: business.v1.AnalyticsService.GetEngagementMetrics:output_type -> business.v1.EngagementMetrics
	7,  // 11: business.v1.AnalyticsService.GetCohortAnalysis:output_type -> business.v1.CohortAnalysis
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_business_v1_analytics_proto_init() }
func file_business_v1_analytics_proto_init() {
	if File_business_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_v1_analytics_proto_rawDesc), len(file_business_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_v1_analytics_proto_goTypes,
		DependencyIndexes: file_business_v1_analytics_proto_depIdxs,
		MessageInfos:      file_business_v1_analytics_proto_msgTypes,
	}.Build()
	File_business_v1_analytics_proto = out.File
	file_business_v1_analytics_proto_goTypes = nil
	file_business_v1_analytics_proto_depIdxs = nil
}
