// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Medhasys LLC
//
// Analytics service contract

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: business/v1/analytics.proto

package businessv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetUserAnalytics_FullMethodName         = "/business.v1.AnalyticsService/GetUserAnalytics"
	AnalyticsService_GetOrganizationAnalytics_FullMethodName = "/business.v1.AnalyticsService/GetOrganizationAnalytics"
	AnalyticsService_GetEngagementMetrics_FullMethodName     = "/business.v1.AnalyticsService/GetEngagementMetrics"
	AnalyticsService_GetCohortAnalysis_FullMethodName        = "/business.v1.AnalyticsService/GetCohortAnalysis"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics service
type AnalyticsServiceClient interface {
	// Get user analytics
	GetUserAnalytics(ctx context.Context, in *GetUserAnalyticsRequest, opts ...grpc.CallOption) (*UserAnalytics, error)
	// Get organization analytics
	GetOrganizationAnalytics(ctx context.Context, in *GetOrganizationAnalyticsRequest, opts ...grpc.CallOption) (*OrganizationAnalytics, error)
	// Get engagement metrics
	GetEngagementMetrics(ctx context.Context, in *GetEngagementRequest, opts ...grpc.CallOption) (*EngagementMetrics, error)
	// Get cohort analysis
	GetCohortAnalysis(ctx context.Context, in *GetCohortRequest, opts ...grpc.CallOption) (*CohortAnalysis, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetUserAnalytics(ctx context.Context, in *GetUserAnalyticsRequest, opts ...grpc.CallOption) (*UserAnalytics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAnalytics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetUserAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOrganizationAnalytics(ctx context.Context, in *GetOrganizationAnalyticsRequest, opts ...grpc.CallOption) (*OrganizationAnalytics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationAnalytics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOrganizationAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetEngagementMetrics(ctx context.Context, in *GetEngagementRequest, opts ...grpc.CallOption) (*EngagementMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EngagementMetrics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetEngagementMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCohortAnalysis(ctx context.Context, in *GetCohortRequest, opts ...grpc.CallOption) (*CohortAnalysis, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CohortAnalysis)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCohortAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// Analytics service
type AnalyticsServiceServer interface {
	// Get user analytics
	GetUserAnalytics(context.Context, *GetUserAnalyticsRequest) (*UserAnalytics, error)
	// Get organization analytics
	GetOrganizationAnalytics(context.Context, *GetOrganizationAnalyticsRequest) (*OrganizationAnalytics, error)
	// Get engagement metrics
	GetEngagementMetrics(context.Context, *GetEngagementRequest) (*EngagementMetrics, error)
	// Get cohort analysis
	GetCohortAnalysis(context.Context, *GetCohortRequest) (*CohortAnalysis, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetUserAnalytics(context.Context, *GetUserAnalyticsRequest) (*UserAnalytics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOrganizationAnalytics(context.Context, *GetOrganizationAnalyticsRequest) (*OrganizationAnalytics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizationAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetEngagementMetrics(context.Context, *GetEngagementRequest) (*EngagementMetrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEngagementMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCohortAnalysis(context.Context, *GetCohortRequest) (*CohortAnalysis, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCohortAnalysis not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetUserAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetUserAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetUserAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetUserAnalytics(ctx, req.(*GetUserAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOrganizationAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOrganizationAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOrganizationAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOrganizationAnalytics(ctx, req.(*GetOrganizationAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetEngagementMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEngagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetEngagementMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetEngagementMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetEngagementMetrics(ctx, req.(*GetEngagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCohortAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCohortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCohortAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCohortAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCohortAnalysis(ctx, req.(*GetCohortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "business.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAnalytics",
			Handler:    _AnalyticsService_GetUserAnalytics_Handler,
		},
		{
			MethodName: "GetOrganizationAnalytics",
			Handler:    _AnalyticsService_GetOrganizationAnalytics_Handler,
		},
		{
			MethodName: "GetEngagementMetrics",
			Handler:    _AnalyticsService_GetEngagementMetrics_Handler,
		},
		{
			MethodName: "GetCohortAnalysis",
			Handler:    _AnalyticsService_GetCohortAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "business/v1/analytics.proto",
}
