// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Medhasys LLC
//
// Billing and subscription service contract

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: business/v1/billing.proto

package businessv1

import (
	v1 "github.com/Arunosaur/ninaivalaigal/shared/contracts/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription tiers
type SubscriptionTier int32

const (
	SubscriptionTier_SUBSCRIPTION_TIER_UNSPECIFIED SubscriptionTier = 0
	SubscriptionTier_SUBSCRIPTION_TIER_FREE        SubscriptionTier = 1
	SubscriptionTier_SUBSCRIPTION_TIER_STARTER     SubscriptionTier = 2
	SubscriptionTier_SUBSCRIPTION_TIER_PRO         SubscriptionTier = 3
	SubscriptionTier_SUBSCRIPTION_TIER_ENTERPRISE  SubscriptionTier = 4
)

// Enum value maps for SubscriptionTier.
var (
	SubscriptionTier_name = map[int32]string{
		0: "SUBSCRIPTION_TIER_UNSPECIFIED",
		1: "SUBSCRIPTION_TIER_FREE",
		2: "SUBSCRIPTION_TIER_STARTER",
		3: "SUBSCRIPTION_TIER_PRO",
		4: "SUBSCRIPTION_TIER_ENTERPRISE",
	}
	SubscriptionTier_value = map[string]int32{
		"SUBSCRIPTION_TIER_UNSPECIFIED": 0,
		"SUBSCRIPTION_TIER_FREE":        1,
		"SUBSCRIPTION_TIER_STARTER":     2,
		"SUBSCRIPTION_TIER_PRO":         3,
		"SUBSCRIPTION_TIER_ENTERPRISE":  4,
	}
)

func (x SubscriptionTier) Enum() *SubscriptionTier {
	p := new(SubscriptionTier)
	*p = x
	return p
}

func (x SubscriptionTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionTier) Descriptor() protoreflect.EnumDescriptor {
	return file_business_v1_billing_proto_enumTypes[0].Descriptor()
}

func (SubscriptionTier) Type() protoreflect.EnumType {
	return &file_business_v1_billing_proto_enumTypes[0]
}

func (x SubscriptionTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionTier.Descriptor instead.
func (SubscriptionTier) EnumDescriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{0}
}

// Subscription status
type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE      SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED   SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_EXPIRED     SubscriptionStatus = 3
	SubscriptionStatus_SUBSCRIPTION_STATUS_TRIAL       SubscriptionStatus = 4
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_ACTIVE",
		2: "SUBSCRIPTION_STATUS_CANCELLED",
		3: "SUBSCRIPTION_STATUS_EXPIRED",
		4: "SUBSCRIPTION_STATUS_TRIAL",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_ACTIVE":      1,
		"SUBSCRIPTION_STATUS_CANCELLED":   2,
		"SUBSCRIPTION_STATUS_EXPIRED":     3,
		"SUBSCRIPTION_STATUS_TRIAL":       4,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_business_v1_billing_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_business_v1_billing_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{1}
}

// Create subscription request
type CreateSubscriptionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Tier            SubscriptionTier       `protobuf:"varint,3,opt,name=tier,proto3,enum=business.v1.SubscriptionTier" json:"tier,omitempty"`
	PaymentMethodId string                 `protobuf:"bytes,4,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetTier() SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return SubscriptionTier_SUBSCRIPTION_TIER_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

// Get subscription request
type GetSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// Update subscription request
type UpdateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	NewTier        SubscriptionTier       `protobuf:"varint,2,opt,name=new_tier,json=newTier,proto3,enum=business.v1.SubscriptionTier" json:"new_tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetNewTier() SubscriptionTier {
	if x != nil {
		return x.NewTier
	}
	return SubscriptionTier_SUBSCRIPTION_TIER_UNSPECIFIED
}

// Cancel subscription request
type CancelSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Immediate      bool                   `protobuf:"varint,2,opt,name=immediate,proto3" json:"immediate,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

func (x *CancelSubscriptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Cancel subscription response
type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EndsAt        string                 `protobuf:"bytes,2,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_business_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CancelSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelSubscriptionResponse) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

// Get usage request
type GetUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetUsageRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetUsageRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// List invoices request
type ListInvoicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_business_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ListInvoicesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListInvoicesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Subscription details
type Subscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Tier           SubscriptionTier       `protobuf:"varint,4,opt,name=tier,proto3,enum=business.v1.SubscriptionTier" json:"tier,omitempty"`
	Status         SubscriptionStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=business.v1.SubscriptionStatus" json:"status,omitempty"`
	StartedAt      string                 `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndsAt         string                 `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	CancelledAt    string                 `protobuf:"bytes,8,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	MonthlyPrice   float64                `protobuf:"fixed64,9,opt,name=monthly_price,json=monthlyPrice,proto3" json:"monthly_price,omitempty"`
	Currency       string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_business_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Subscription) GetTier() SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return SubscriptionTier_SUBSCRIPTION_TIER_UNSPECIFIED
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Subscription) GetEndsAt() string {
	if x != nil {
		return x.EndsAt
	}
	return ""
}

func (x *Subscription) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

func (x *Subscription) GetMonthlyPrice() float64 {
	if x != nil {
		return x.MonthlyPrice
	}
	return 0
}

func (x *Subscription) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Usage report
type UsageReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ApiCalls       int64                  `protobuf:"varint,2,opt,name=api_calls,json=apiCalls,proto3" json:"api_calls,omitempty"`
	MemoryCount    int64                  `protobuf:"varint,3,opt,name=memory_count,json=memoryCount,proto3" json:"memory_count,omitempty"`
	StorageBytes   int64                  `protobuf:"varint,4,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	Cost           float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	PeriodStart    string                 `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      string                 `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_business_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *UsageReport) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UsageReport) GetApiCalls() int64 {
	if x != nil {
		return x.ApiCalls
	}
	return 0
}

func (x *UsageReport) GetMemoryCount() int64 {
	if x != nil {
		return x.MemoryCount
	}
	return 0
}

func (x *UsageReport) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *UsageReport) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *UsageReport) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *UsageReport) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

// Invoice list response
type InvoiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceList) Reset() {
	*x = InvoiceList{}
	mi := &file_business_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceList) ProtoMessage() {}

func (x *InvoiceList) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceList.ProtoReflect.Descriptor instead.
func (*InvoiceList) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *InvoiceList) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *InvoiceList) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// Invoice details
type Invoice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DueDate        string                 `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	PaidAt         string                 `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	PdfUrl         string                 `protobuf:"bytes,8,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_business_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_business_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Invoice) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Invoice) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Invoice) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

var File_business_v1_billing_proto protoreflect.FileDescriptor

const file_business_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x19business/v1/billing.proto\x12\vbusiness.v1\x1a\x16common/v1/errors.proto\x1a\x1acommon/v1/pagination.proto\"\xbc\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x121\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x1d.business.v1.SubscriptionTierR\x04tier\x12*\n" +
	"\x11payment_method_id\x18\x04 \x01(\tR\x0fpaymentMethodId\"A\n" +
	"\x16GetSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"~\n" +
	"\x19UpdateSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x128\n" +
	"\bnew_tier\x18\x02 \x01(\x0e2\x1d.business.v1.SubscriptionTierR\anewTier\"z\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\timmediate\x18\x02 \x01(\bR\timmediate\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"O\n" +
	"\x1aCancelSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aends_at\x18\x02 \x01(\tR\x06endsAt\"t\n" +
	"\x0fGetUsageRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"j\n" +
	"\x13ListInvoicesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestR\x04page\"\xe8\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x121\n" +
	"\x04tier\x18\x04 \x01(\x0e2\x1d.business.v1.SubscriptionTierR\x04tier\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.business.v1.SubscriptionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\x12\x17\n" +
	"\aends_at\x18\a \x01(\tR\x06endsAt\x12!\n" +
	"\fcancelled_at\x18\b \x01(\tR\vcancelledAt\x12#\n" +
	"\rmonthly_price\x18\t \x01(\x01R\fmonthlyPrice\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\"\xf1\x01\n" +
	"\vUsageReport\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tapi_calls\x18\x02 \x01(\x03R\bapiCalls\x12!\n" +
	"\fmemory_count\x18\x03 \x01(\x03R\vmemoryCount\x12#\n" +
	"\rstorage_bytes\x18\x04 \x01(\x03R\fstorageBytes\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12!\n" +
	"\fperiod_start\x18\x06 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\a \x01(\tR\tperiodEnd\"q\n" +
	"\vInvoiceList\x120\n" +
	"\binvoices\x18\x01 \x03(\v2\x14.business.v1.InvoiceR\binvoices\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo\"\xdb\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\bdue_date\x18\x06 \x01(\tR\adueDate\x12\x17\n" +
	"\apaid_at\x18\a \x01(\tR\x06paidAt\x12\x17\n" +
	"\apdf_url\x18\b \x01(\tR\x06pdfUrl*\xad\x01\n" +
	"\x10SubscriptionTier\x12!\n" +
	"\x1dSUBSCRIPTION_TIER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SUBSCRIPTION_TIER_FREE\x10\x01\x12\x1d\n" +
	"\x19SUBSCRIPTION_TIER_STARTER\x10\x02\x12\x19\n" +
	"\x15SUBSCRIPTION_TIER_PRO\x10\x03\x12 \n" +
	"\x1cSUBSCRIPTION_TIER_ENTERPRISE\x10\x04*\xbc\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x01\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x02\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_EXPIRED\x10\x03\x12\x1d\n" +
	"\x19SUBSCRIPTION_STATUS_TRIAL\x10\x042\x8c\x04\n" +
	"\x0eBillingService\x12W\n" +
	"\x12CreateSubscription\x12&.business.v1.CreateSubscriptionRequest\x1a\x19.business.v1.Subscription\x12Q\n" +
	"\x0fGetSubscription\x12#.business.v1.GetSubscriptionRequest\x1a\x19.business.v1.Subscription\x12W\n" +
	"\x12UpdateSubscription\x12&.business.v1.UpdateSubscriptionRequest\x1a\x19.business.v1.Subscription\x12e\n" +
	"\x12CancelSubscription\x12&.business.v1.CancelSubscriptionRequest\x1a'.business.v1.CancelSubscriptionResponse\x12B\n" +
	"\bGetUsage\x12\x1c.business.v1.GetUsageRequest\x1a\x18.business.v1.UsageReport\x12J\n" +
	"\fListInvoices\x12 .business.v1.ListInvoicesRequest\x1a\x18.business.v1.InvoiceListBLZJgithub.com/Arunosaur/ninaivalaigal/shared/contracts/business/v1;businessv1b\x06proto3"

var (
	file_business_v1_billing_proto_rawDescOnce sync.Once
	file_business_v1_billing_proto_rawDescData []byte
)

func file_business_v1_billing_proto_rawDescGZIP() []byte {
	file_business_v1_billing_proto_rawDescOnce.Do(func() {
		file_business_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_v1_billing_proto_rawDesc), len(file_business_v1_billing_proto_rawDesc)))
	})
	return file_business_v1_billing_proto_rawDescData
}

var file_business_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_business_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_business_v1_billing_proto_goTypes = []any{
	(SubscriptionTier)(0),              // 0: business.v1.SubscriptionTier
	(SubscriptionStatus)(0),            // 1: business.v1.SubscriptionStatus
	(*CreateSubscriptionRequest)(nil),  // 2: business.v1.CreateSubscriptionRequest
	(*GetSubscriptionRequest)(nil),     // 3: business.v1.GetSubscriptionRequest
	(*UpdateSubscriptionRequest)(nil),  // 4: business.v1.UpdateSubscriptionRequest
	(*CancelSubscriptionRequest)(nil),  // 5: business.v1.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil), // 6: business.v1.CancelSubscriptionResponse
	(*GetUsageRequest)(nil),            // 7: business.v1.GetUsageRequest
	(*ListInvoicesRequest)(nil),        // 8: business.v1.ListInvoicesRequest
	(*Subscription)(nil),               // 9: business.v1.Subscription
	(*UsageReport)(nil),                // 10: business.v1.UsageReport
	(*InvoiceList)(nil),                // 11: business.v1.InvoiceList
	(*Invoice)(nil),                    // 12: business.v1.Invoice
	(*v1.PageRequest)(nil),             // 13: common.v1.PageRequest
	(*v1.PageInfo)(nil),                // 14: common.v1.PageInfo
}
var file_business_v1_billing_proto_depIdxs = []int32{
	0,  // 0: business.v1.CreateSubscriptionRequest.tier:type_name -> business.v1.SubscriptionTier
	0,  // 1: business.v1.UpdateSubscriptionRequest.new_tier:type_name -> business.v1.SubscriptionTier
	13, // 2: business.v1.ListInvoicesRequest.page:type_name -> common.v1.PageRequest
	0,  // 3: business.v1.Subscription.tier:type_name -> business.v1.SubscriptionTier
	1,  // 4: business.v1.Subscription.status:type_name -> business.v1.SubscriptionStatus
	12, // 5: business.v1.InvoiceList.invoices:type_name -> business.v1.Invoice
	14, // 6: business.v1.InvoiceList.page_info:type_name -> common.v1.PageInfo
	2,  // 7: business.v1.BillingService.CreateSubscription:input_type -> business.v1.CreateSubscriptionRequest
	3,  // 8: business.v1.BillingService.GetSubscription:input_type -> business.v1.GetSubscriptionRequest
	4,  // 9: business.v1.BillingService.UpdateSubscription:input_type -> business.v1.UpdateSubscriptionRequest
	5,  // 10: business.v1.BillingService.CancelSubscription:input_type -> business.v1.CancelSubscriptionRequest
	7,  // 11: business.v1.BillingService.GetUsage:input_type -> business.v1.GetUsageRequest
	8,  // 12: business.v1.BillingService.ListInvoices:input_type -> business.v1.ListInvoicesRequest
	9,  // 13: business.v1.BillingService.CreateSubscription:output_type -> business.v1.Subscription
	9,  // 14: business.v1.BillingService.GetSubscription:output_type -> business.v1.Subscription
	9,  // 15: business.v1.BillingService.UpdateSubscription:output_type -> business.v1.Subscription
	6,  // 16: business.v1.BillingService.CancelSubscription:output_type -> business.v1.CancelSubscriptionResponse
	10, // 17: business.v1.BillingService.GetUsage:output_type -> business.v1.UsageReport
	11, // 18: business.v1.BillingService.ListInvoices:output_type -> business.v1.InvoiceList
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_business_v1_billing_proto_init() }
func file_business_v1_billing_proto_init() {
	if File_business_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_v1_billing_proto_rawDesc), len(file_business_v1_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_v1_billing_proto_goTypes,
		DependencyIndexes: file_business_v1_billing_proto_depIdxs,
		EnumInfos:         file_business_v1_billing_proto_enumTypes,
		MessageInfos:      file_business_v1_billing_proto_msgTypes,
	}.Build()
	File_business_v1_billing_proto = out.File
	file_business_v1_billing_proto_goTypes = nil
	file_business_v1_billing_proto_depIdxs = nil
}
