#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Medhasys LLC
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from business.v1 import billing_pb2 as business_dot_v1_dot_billing__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in business/v1/billing_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BillingServiceStub(object):
    """Billing service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSubscription = channel.unary_unary(
            "/business.v1.BillingService/CreateSubscription",
            request_serializer=business_dot_v1_dot_billing__pb2.CreateSubscriptionRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.Subscription.FromString,
            _registered_method=True,
        )
        self.GetSubscription = channel.unary_unary(
            "/business.v1.BillingService/GetSubscription",
            request_serializer=business_dot_v1_dot_billing__pb2.GetSubscriptionRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.Subscription.FromString,
            _registered_method=True,
        )
        self.UpdateSubscription = channel.unary_unary(
            "/business.v1.BillingService/UpdateSubscription",
            request_serializer=business_dot_v1_dot_billing__pb2.UpdateSubscriptionRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.Subscription.FromString,
            _registered_method=True,
        )
        self.CancelSubscription = channel.unary_unary(
            "/business.v1.BillingService/CancelSubscription",
            request_serializer=business_dot_v1_dot_billing__pb2.CancelSubscriptionRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.CancelSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.GetUsage = channel.unary_unary(
            "/business.v1.BillingService/GetUsage",
            request_serializer=business_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.UsageReport.FromString,
            _registered_method=True,
        )
        self.ListInvoices = channel.unary_unary(
            "/business.v1.BillingService/ListInvoices",
            request_serializer=business_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
            response_deserializer=business_dot_v1_dot_billing__pb2.InvoiceList.FromString,
            _registered_method=True,
        )


class BillingServiceServicer(object):
    """Billing service"""

    def CreateSubscription(self, request, context):
        """Create a new subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSubscription(self, request, context):
        """Get subscription details"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateSubscription(self, request, context):
        """Update subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelSubscription(self, request, context):
        """Cancel subscription"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUsage(self, request, context):
        """Get usage report"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListInvoices(self, request, context):
        """List invoices"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSubscription,
            request_deserializer=business_dot_v1_dot_billing__pb2.CreateSubscriptionRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.Subscription.SerializeToString,
        ),
        "GetSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscription,
            request_deserializer=business_dot_v1_dot_billing__pb2.GetSubscriptionRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.Subscription.SerializeToString,
        ),
        "UpdateSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateSubscription,
            request_deserializer=business_dot_v1_dot_billing__pb2.UpdateSubscriptionRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.Subscription.SerializeToString,
        ),
        "CancelSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.CancelSubscription,
            request_deserializer=business_dot_v1_dot_billing__pb2.CancelSubscriptionRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.CancelSubscriptionResponse.SerializeToString,
        ),
        "GetUsage": grpc.unary_unary_rpc_method_handler(
            servicer.GetUsage,
            request_deserializer=business_dot_v1_dot_billing__pb2.GetUsageRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.UsageReport.SerializeToString,
        ),
        "ListInvoices": grpc.unary_unary_rpc_method_handler(
            servicer.ListInvoices,
            request_deserializer=business_dot_v1_dot_billing__pb2.ListInvoicesRequest.FromString,
            response_serializer=business_dot_v1_dot_billing__pb2.InvoiceList.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("business.v1.BillingService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("business.v1.BillingService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Billing service"""

    @staticmethod
    def CreateSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/CreateSubscription",
            business_dot_v1_dot_billing__pb2.CreateSubscriptionRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/GetSubscription",
            business_dot_v1_dot_billing__pb2.GetSubscriptionRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/UpdateSubscription",
            business_dot_v1_dot_billing__pb2.UpdateSubscriptionRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/CancelSubscription",
            business_dot_v1_dot_billing__pb2.CancelSubscriptionRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.CancelSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUsage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/GetUsage",
            business_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.UsageReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListInvoices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/business.v1.BillingService/ListInvoices",
            business_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
            business_dot_v1_dot_billing__pb2.InvoiceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
