# SPDX-License-Identifier: Proprietary
# Copyright (c) 2025 Medhasys LLC

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graphops.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "graphops.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0egraphops.proto\x12\x0bgraphops.v1"$\n\x13\x45xecuteQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t"$\n\x14\x45xecuteQueryResponse\x12\x0c\n\x04rows\x18\x01 \x03(\t2_\n\x08GraphOps\x12S\n\x0c\x45xecuteQuery\x12 .graphops.v1.ExecuteQueryRequest\x1a!.graphops.v1.ExecuteQueryResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "graphops_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EXECUTEQUERYREQUEST"]._serialized_start = 31
    _globals["_EXECUTEQUERYREQUEST"]._serialized_end = 67
    _globals["_EXECUTEQUERYRESPONSE"]._serialized_start = 69
    _globals["_EXECUTEQUERYRESPONSE"]._serialized_end = 105
    _globals["_GRAPHOPS"]._serialized_start = 107
    _globals["_GRAPHOPS"]._serialized_end = 202
# @@protoc_insertion_point(module_scope)
