# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from graph.v1 import graphops_pb2 as graph_dot_v1_dot_graphops__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in graph/v1/graphops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphOpsServiceStub(object):
    """GraphOps Service - gRPC definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteQuery',
                request_serializer=graph_dot_v1_dot_graphops__pb2.ExecuteQueryRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graphops__pb2.ExecuteQueryResponse.FromString,
                _registered_method=True)
        self.ExecuteTransaction = channel.unary_unary(
                '/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteTransaction',
                request_serializer=graph_dot_v1_dot_graphops__pb2.ExecuteTransactionRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graphops__pb2.ExecuteTransactionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ninaivalaigal.graphops.v1.GraphOpsService/HealthCheck',
                request_serializer=graph_dot_v1_dot_graphops__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graphops__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetGraphStats = channel.unary_unary(
                '/ninaivalaigal.graphops.v1.GraphOpsService/GetGraphStats',
                request_serializer=graph_dot_v1_dot_graphops__pb2.GetGraphStatsRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graphops__pb2.GetGraphStatsResponse.FromString,
                _registered_method=True)


class GraphOpsServiceServicer(object):
    """GraphOps Service - gRPC definitions
    """

    def ExecuteQuery(self, request, context):
        """Execute a Cypher query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTransaction(self, request, context):
        """Execute multiple queries in a transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphStats(self, request, context):
        """Get graph statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphOpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=graph_dot_v1_dot_graphops__pb2.ExecuteQueryRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graphops__pb2.ExecuteQueryResponse.SerializeToString,
            ),
            'ExecuteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransaction,
                    request_deserializer=graph_dot_v1_dot_graphops__pb2.ExecuteTransactionRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graphops__pb2.ExecuteTransactionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=graph_dot_v1_dot_graphops__pb2.HealthCheckRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graphops__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetGraphStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphStats,
                    request_deserializer=graph_dot_v1_dot_graphops__pb2.GetGraphStatsRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graphops__pb2.GetGraphStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ninaivalaigal.graphops.v1.GraphOpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ninaivalaigal.graphops.v1.GraphOpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphOpsService(object):
    """GraphOps Service - gRPC definitions
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteQuery',
            graph_dot_v1_dot_graphops__pb2.ExecuteQueryRequest.SerializeToString,
            graph_dot_v1_dot_graphops__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteTransaction',
            graph_dot_v1_dot_graphops__pb2.ExecuteTransactionRequest.SerializeToString,
            graph_dot_v1_dot_graphops__pb2.ExecuteTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ninaivalaigal.graphops.v1.GraphOpsService/HealthCheck',
            graph_dot_v1_dot_graphops__pb2.HealthCheckRequest.SerializeToString,
            graph_dot_v1_dot_graphops__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ninaivalaigal.graphops.v1.GraphOpsService/GetGraphStats',
            graph_dot_v1_dot_graphops__pb2.GetGraphStatsRequest.SerializeToString,
            graph_dot_v1_dot_graphops__pb2.GetGraphStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
