version = 1

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x"

  [analyzers.meta]
  max_line_length = 100

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "typescript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "**/.venv/**",
  ".tox/**",
  ".mypy_cache/**",
  ".ruff_cache/**"
]

[transformers]
enabled = []

[baseline]
