apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ninaivalaigal
  namespace: argocd
  labels:
    app.kubernetes.io/name: ninaivalaigal
    app.kubernetes.io/part-of: ninaivalaigal-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Arunosaur/ninaivalaigal
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ninaivalaigal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
# AppProject for ninaivalaigal (optional, for more control)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ninaivalaigal-project
  namespace: argocd
  labels:
    app.kubernetes.io/name: ninaivalaigal-project
    app.kubernetes.io/part-of: ninaivalaigal-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Ninaivalaigal AI Memory Platform
  sourceRepos:
  - 'https://github.com/Arunosaur/ninaivalaigal'
  destinations:
  - namespace: ninaivalaigal
    server: https://kubernetes.default.svc
  - namespace: ninaivalaigal-*
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: ServiceAccount
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  roles:
  - name: read-only
    description: Read-only privileges to ninaivalaigal project
    policies:
    - p, proj:ninaivalaigal-project:read-only, applications, get, ninaivalaigal-project/*, allow
    - p, proj:ninaivalaigal-project:read-only, applications, sync, ninaivalaigal-project/*, deny
    groups:
    - ninaivalaigal:viewers
  - name: admin
    description: Admin privileges to ninaivalaigal project
    policies:
    - p, proj:ninaivalaigal-project:admin, applications, *, ninaivalaigal-project/*, allow
    - p, proj:ninaivalaigal-project:admin, repositories, *, *, allow
    groups:
    - ninaivalaigal:admins
