// SPDX-License-Identifier: Proprietary
// Copyright (c) 2025 Medhasys LLC
//
// GraphOps Service Contract - Apache AGE Cypher Query Execution
// SPEC-099/100: Runtime-agnostic gRPC interface for graph operations
//
// Version: v1
// Status: Draft
// Authors: Developer C, Developer A

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: graphops/v1/graphops.proto

package graphopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphOpsService_ExecuteQuery_FullMethodName      = "/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteQuery"
	GraphOpsService_ExecuteQueryBatch_FullMethodName = "/ninaivalaigal.graphops.v1.GraphOpsService/ExecuteQueryBatch"
	GraphOpsService_HealthCheck_FullMethodName       = "/ninaivalaigal.graphops.v1.GraphOpsService/HealthCheck"
	GraphOpsService_GetMetrics_FullMethodName        = "/ninaivalaigal.graphops.v1.GraphOpsService/GetMetrics"
)

// GraphOpsServiceClient is the client API for GraphOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # GraphOps Service - High-performance Apache AGE query execution
//
// This service provides a unified interface for executing Cypher queries
// against Apache AGE graphs, supporting both Python and Rust runtimes.
type GraphOpsServiceClient interface {
	// Execute a Cypher query against the configured graph
	ExecuteQuery(ctx context.Context, in *CypherRequest, opts ...grpc.CallOption) (*CypherResponse, error)
	// Execute a batch of Cypher queries (optimized for multiple operations)
	ExecuteQueryBatch(ctx context.Context, in *CypherBatchRequest, opts ...grpc.CallOption) (*CypherBatchResponse, error)
	// Health check endpoint for service monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Get service performance metrics
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type graphOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphOpsServiceClient(cc grpc.ClientConnInterface) GraphOpsServiceClient {
	return &graphOpsServiceClient{cc}
}

func (c *graphOpsServiceClient) ExecuteQuery(ctx context.Context, in *CypherRequest, opts ...grpc.CallOption) (*CypherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CypherResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) ExecuteQueryBatch(ctx context.Context, in *CypherBatchRequest, opts ...grpc.CallOption) (*CypherBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CypherBatchResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_ExecuteQueryBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphOpsServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, GraphOpsService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphOpsServiceServer is the server API for GraphOpsService service.
// All implementations must embed UnimplementedGraphOpsServiceServer
// for forward compatibility.
//
// # GraphOps Service - High-performance Apache AGE query execution
//
// This service provides a unified interface for executing Cypher queries
// against Apache AGE graphs, supporting both Python and Rust runtimes.
type GraphOpsServiceServer interface {
	// Execute a Cypher query against the configured graph
	ExecuteQuery(context.Context, *CypherRequest) (*CypherResponse, error)
	// Execute a batch of Cypher queries (optimized for multiple operations)
	ExecuteQueryBatch(context.Context, *CypherBatchRequest) (*CypherBatchResponse, error)
	// Health check endpoint for service monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Get service performance metrics
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedGraphOpsServiceServer()
}

// UnimplementedGraphOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphOpsServiceServer struct{}

func (UnimplementedGraphOpsServiceServer) ExecuteQuery(context.Context, *CypherRequest) (*CypherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedGraphOpsServiceServer) ExecuteQueryBatch(context.Context, *CypherBatchRequest) (*CypherBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQueryBatch not implemented")
}
func (UnimplementedGraphOpsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGraphOpsServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedGraphOpsServiceServer) mustEmbedUnimplementedGraphOpsServiceServer() {}
func (UnimplementedGraphOpsServiceServer) testEmbeddedByValue()                         {}

// UnsafeGraphOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphOpsServiceServer will
// result in compilation errors.
type UnsafeGraphOpsServiceServer interface {
	mustEmbedUnimplementedGraphOpsServiceServer()
}

func RegisterGraphOpsServiceServer(s grpc.ServiceRegistrar, srv GraphOpsServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraphOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphOpsService_ServiceDesc, srv)
}

func _GraphOpsService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CypherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).ExecuteQuery(ctx, req.(*CypherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_ExecuteQueryBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CypherBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).ExecuteQueryBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_ExecuteQueryBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).ExecuteQueryBatch(ctx, req.(*CypherBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphOpsService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphOpsServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphOpsService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphOpsServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphOpsService_ServiceDesc is the grpc.ServiceDesc for GraphOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ninaivalaigal.graphops.v1.GraphOpsService",
	HandlerType: (*GraphOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _GraphOpsService_ExecuteQuery_Handler,
		},
		{
			MethodName: "ExecuteQueryBatch",
			Handler:    _GraphOpsService_ExecuteQueryBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GraphOpsService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _GraphOpsService_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graphops/v1/graphops.proto",
}
