// SPDX-License-Identifier: Proprietary
// Copyright (c) 2025 Medhasys LLC
//
// GraphOps Service Contract - Apache AGE Cypher Query Execution
// SPEC-099/100: Runtime-agnostic gRPC interface for graph operations
//
// Version: v1
// Status: Draft
// Authors: Developer C, Developer A

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: graphops/v1/graphops.proto

package graphopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query execution status
type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_SUCCESS     ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_ERROR       ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_TIMEOUT     ExecutionStatus = 3
	ExecutionStatus_EXECUTION_STATUS_PARTIAL     ExecutionStatus = 4 // Some queries succeeded in batch
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_SUCCESS",
		2: "EXECUTION_STATUS_ERROR",
		3: "EXECUTION_STATUS_TIMEOUT",
		4: "EXECUTION_STATUS_PARTIAL",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_SUCCESS":     1,
		"EXECUTION_STATUS_ERROR":       2,
		"EXECUTION_STATUS_TIMEOUT":     3,
		"EXECUTION_STATUS_PARTIAL":     4,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graphops_v1_graphops_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_graphops_v1_graphops_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{0}
}

// Health status
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_graphops_v1_graphops_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_graphops_v1_graphops_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{1}
}

// Request to execute a single Cypher query
type CypherRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cypher query string (e.g., "MATCH (n:User) RETURN n LIMIT 10")
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional parameters for parameterized queries
	// Key: parameter name, Value: JSON-encoded parameter value
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional timeout in milliseconds (default: 30000)
	TimeoutMs int32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Request tracing ID for distributed tracing (OpenTelemetry)
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Request span ID for distributed tracing
	SpanId        string `protobuf:"bytes,5,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CypherRequest) Reset() {
	*x = CypherRequest{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CypherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CypherRequest) ProtoMessage() {}

func (x *CypherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CypherRequest.ProtoReflect.Descriptor instead.
func (*CypherRequest) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{0}
}

func (x *CypherRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CypherRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CypherRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CypherRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CypherRequest) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

// Response containing query results
type CypherResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query execution status
	Status ExecutionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ninaivalaigal.graphops.v1.ExecutionStatus" json:"status,omitempty"`
	// Result rows as JSON-encoded strings
	// Each element is a JSON object representing one result row
	Results []string `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// Execution time in milliseconds
	ExecutionTimeMs int32 `protobuf:"varint,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// Number of rows returned
	RowCount int32 `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// Error details if status is ERROR
	Error *ErrorDetails `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Performance metrics for this query
	Metrics       *QueryMetrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CypherResponse) Reset() {
	*x = CypherResponse{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CypherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CypherResponse) ProtoMessage() {}

func (x *CypherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CypherResponse.ProtoReflect.Descriptor instead.
func (*CypherResponse) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{1}
}

func (x *CypherResponse) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *CypherResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CypherResponse) GetExecutionTimeMs() int32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *CypherResponse) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *CypherResponse) GetError() *ErrorDetails {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CypherResponse) GetMetrics() *QueryMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Request to execute multiple queries in batch
type CypherBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of queries to execute
	Queries []*CypherRequest `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	// Whether to stop on first error (default: false, continue on error)
	FailFast bool `protobuf:"varint,2,opt,name=fail_fast,json=failFast,proto3" json:"fail_fast,omitempty"`
	// Request tracing ID for the entire batch
	TraceId       string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CypherBatchRequest) Reset() {
	*x = CypherBatchRequest{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CypherBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CypherBatchRequest) ProtoMessage() {}

func (x *CypherBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CypherBatchRequest.ProtoReflect.Descriptor instead.
func (*CypherBatchRequest) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{2}
}

func (x *CypherBatchRequest) GetQueries() []*CypherRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *CypherBatchRequest) GetFailFast() bool {
	if x != nil {
		return x.FailFast
	}
	return false
}

func (x *CypherBatchRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// Response for batch query execution
type CypherBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Individual responses for each query (in order)
	Responses []*CypherResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	// Overall batch status
	BatchStatus ExecutionStatus `protobuf:"varint,2,opt,name=batch_status,json=batchStatus,proto3,enum=ninaivalaigal.graphops.v1.ExecutionStatus" json:"batch_status,omitempty"`
	// Total execution time for entire batch
	TotalExecutionTimeMs int32 `protobuf:"varint,3,opt,name=total_execution_time_ms,json=totalExecutionTimeMs,proto3" json:"total_execution_time_ms,omitempty"`
	// Number of successful queries
	SuccessCount int32 `protobuf:"varint,4,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// Number of failed queries
	FailureCount  int32 `protobuf:"varint,5,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CypherBatchResponse) Reset() {
	*x = CypherBatchResponse{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CypherBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CypherBatchResponse) ProtoMessage() {}

func (x *CypherBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CypherBatchResponse.ProtoReflect.Descriptor instead.
func (*CypherBatchResponse) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{3}
}

func (x *CypherBatchResponse) GetResponses() []*CypherResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *CypherBatchResponse) GetBatchStatus() ExecutionStatus {
	if x != nil {
		return x.BatchStatus
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *CypherBatchResponse) GetTotalExecutionTimeMs() int32 {
	if x != nil {
		return x.TotalExecutionTimeMs
	}
	return 0
}

func (x *CypherBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *CypherBatchResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

// Health check request
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional service name to check (empty = check all)
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// Health check response
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ninaivalaigal.graphops.v1.HealthStatus" json:"status,omitempty"`
	// Database connection status
	Database *ComponentStatus `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Apache AGE extension status
	AgeExtension *ComponentStatus `protobuf:"bytes,3,opt,name=age_extension,json=ageExtension,proto3" json:"age_extension,omitempty"`
	// Service uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Service version
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Additional health details
	Details       map[string]string `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetDatabase() *ComponentStatus {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *HealthCheckResponse) GetAgeExtension() *ComponentStatus {
	if x != nil {
		return x.AgeExtension
	}
	return nil
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// Metrics request
type MetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time window for metrics (in seconds, default: 300)
	WindowSeconds int32 `protobuf:"varint,1,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

// Metrics response
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total queries executed in window
	TotalQueries int64 `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	// Successful queries in window
	SuccessfulQueries int64 `protobuf:"varint,2,opt,name=successful_queries,json=successfulQueries,proto3" json:"successful_queries,omitempty"`
	// Failed queries in window
	FailedQueries int64 `protobuf:"varint,3,opt,name=failed_queries,json=failedQueries,proto3" json:"failed_queries,omitempty"`
	// P50 latency in milliseconds
	P50LatencyMs float64 `protobuf:"fixed64,4,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	// P95 latency in milliseconds
	P95LatencyMs float64 `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	// P99 latency in milliseconds
	P99LatencyMs float64 `protobuf:"fixed64,6,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	// Average query execution time in milliseconds
	AvgExecutionTimeMs float64 `protobuf:"fixed64,7,opt,name=avg_execution_time_ms,json=avgExecutionTimeMs,proto3" json:"avg_execution_time_ms,omitempty"`
	// Current memory usage in bytes
	MemoryUsageBytes int64 `protobuf:"varint,8,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	// Active connections count
	ActiveConnections int32 `protobuf:"varint,9,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsResponse) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *MetricsResponse) GetSuccessfulQueries() int64 {
	if x != nil {
		return x.SuccessfulQueries
	}
	return 0
}

func (x *MetricsResponse) GetFailedQueries() int64 {
	if x != nil {
		return x.FailedQueries
	}
	return 0
}

func (x *MetricsResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *MetricsResponse) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *MetricsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *MetricsResponse) GetAvgExecutionTimeMs() float64 {
	if x != nil {
		return x.AvgExecutionTimeMs
	}
	return 0
}

func (x *MetricsResponse) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *MetricsResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// Component health status
type ComponentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Component health
	Status HealthStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ninaivalaigal.graphops.v1.HealthStatus" json:"status,omitempty"`
	// Error message if unhealthy
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Last check timestamp (Unix epoch seconds)
	LastCheckTimestamp int64 `protobuf:"varint,4,opt,name=last_check_timestamp,json=lastCheckTimestamp,proto3" json:"last_check_timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentStatus) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *ComponentStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ComponentStatus) GetLastCheckTimestamp() int64 {
	if x != nil {
		return x.LastCheckTimestamp
	}
	return 0
}

// Error details
type ErrorDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code (e.g., "QUERY_SYNTAX_ERROR", "CONNECTION_FAILED")
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Stack trace (only in debug mode)
	StackTrace string `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// SQL state code (PostgreSQL)
	SqlState string `protobuf:"bytes,4,opt,name=sql_state,json=sqlState,proto3" json:"sql_state,omitempty"`
	// Additional error context
	Context       map[string]string `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorDetails) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ErrorDetails) GetSqlState() string {
	if x != nil {
		return x.SqlState
	}
	return ""
}

func (x *ErrorDetails) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Query performance metrics
type QueryMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time spent in query parsing (ms)
	ParseTimeMs float64 `protobuf:"fixed64,1,opt,name=parse_time_ms,json=parseTimeMs,proto3" json:"parse_time_ms,omitempty"`
	// Time spent in query planning (ms)
	PlanTimeMs float64 `protobuf:"fixed64,2,opt,name=plan_time_ms,json=planTimeMs,proto3" json:"plan_time_ms,omitempty"`
	// Time spent in query execution (ms)
	ExecutionTimeMs float64 `protobuf:"fixed64,3,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// Number of rows scanned
	RowsScanned int64 `protobuf:"varint,4,opt,name=rows_scanned,json=rowsScanned,proto3" json:"rows_scanned,omitempty"`
	// Number of rows returned
	RowsReturned int64 `protobuf:"varint,5,opt,name=rows_returned,json=rowsReturned,proto3" json:"rows_returned,omitempty"`
	// Memory used by query (bytes)
	MemoryUsedBytes int64 `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	// Whether query hit cache
	CacheHit      bool `protobuf:"varint,7,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetrics) Reset() {
	*x = QueryMetrics{}
	mi := &file_graphops_v1_graphops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetrics) ProtoMessage() {}

func (x *QueryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_graphops_v1_graphops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetrics.ProtoReflect.Descriptor instead.
func (*QueryMetrics) Descriptor() ([]byte, []int) {
	return file_graphops_v1_graphops_proto_rawDescGZIP(), []int{10}
}

func (x *QueryMetrics) GetParseTimeMs() float64 {
	if x != nil {
		return x.ParseTimeMs
	}
	return 0
}

func (x *QueryMetrics) GetPlanTimeMs() float64 {
	if x != nil {
		return x.PlanTimeMs
	}
	return 0
}

func (x *QueryMetrics) GetExecutionTimeMs() float64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *QueryMetrics) GetRowsScanned() int64 {
	if x != nil {
		return x.RowsScanned
	}
	return 0
}

func (x *QueryMetrics) GetRowsReturned() int64 {
	if x != nil {
		return x.RowsReturned
	}
	return 0
}

func (x *QueryMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *QueryMetrics) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

var File_graphops_v1_graphops_proto protoreflect.FileDescriptor

const file_graphops_v1_graphops_proto_rawDesc = "" +
	"\n" +
	"\x1agraphops/v1/graphops.proto\x12\x19ninaivalaigal.graphops.v1\"\x91\x02\n" +
	"\rCypherRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12X\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v28.ninaivalaigal.graphops.v1.CypherRequest.ParametersEntryR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x05 \x01(\tR\x06spanId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x02\n" +
	"\x0eCypherResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.ninaivalaigal.graphops.v1.ExecutionStatusR\x06status\x12\x18\n" +
	"\aresults\x18\x02 \x03(\tR\aresults\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x05R\x0fexecutionTimeMs\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x05R\browCount\x12=\n" +
	"\x05error\x18\x05 \x01(\v2'.ninaivalaigal.graphops.v1.ErrorDetailsR\x05error\x12A\n" +
	"\ametrics\x18\x06 \x01(\v2'.ninaivalaigal.graphops.v1.QueryMetricsR\ametrics\"\x90\x01\n" +
	"\x12CypherBatchRequest\x12B\n" +
	"\aqueries\x18\x01 \x03(\v2(.ninaivalaigal.graphops.v1.CypherRequestR\aqueries\x12\x1b\n" +
	"\tfail_fast\x18\x02 \x01(\bR\bfailFast\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\xae\x02\n" +
	"\x13CypherBatchResponse\x12G\n" +
	"\tresponses\x18\x01 \x03(\v2).ninaivalaigal.graphops.v1.CypherResponseR\tresponses\x12M\n" +
	"\fbatch_status\x18\x02 \x01(\x0e2*.ninaivalaigal.graphops.v1.ExecutionStatusR\vbatchStatus\x125\n" +
	"\x17total_execution_time_ms\x18\x03 \x01(\x05R\x14totalExecutionTimeMs\x12#\n" +
	"\rsuccess_count\x18\x04 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x05 \x01(\x05R\ffailureCount\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xc3\x03\n" +
	"\x13HealthCheckResponse\x12?\n" +
	"\x06status\x18\x01 \x01(\x0e2'.ninaivalaigal.graphops.v1.HealthStatusR\x06status\x12F\n" +
	"\bdatabase\x18\x02 \x01(\v2*.ninaivalaigal.graphops.v1.ComponentStatusR\bdatabase\x12O\n" +
	"\rage_extension\x18\x03 \x01(\v2*.ninaivalaigal.graphops.v1.ComponentStatusR\fageExtension\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12U\n" +
	"\adetails\x18\x06 \x03(\v2;.ninaivalaigal.graphops.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x0eMetricsRequest\x12%\n" +
	"\x0ewindow_seconds\x18\x01 \x01(\x05R\rwindowSeconds\"\x8e\x03\n" +
	"\x0fMetricsResponse\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x03R\ftotalQueries\x12-\n" +
	"\x12successful_queries\x18\x02 \x01(\x03R\x11successfulQueries\x12%\n" +
	"\x0efailed_queries\x18\x03 \x01(\x03R\rfailedQueries\x12$\n" +
	"\x0ep50_latency_ms\x18\x04 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x06 \x01(\x01R\fp99LatencyMs\x121\n" +
	"\x15avg_execution_time_ms\x18\a \x01(\x01R\x12avgExecutionTimeMs\x12,\n" +
	"\x12memory_usage_bytes\x18\b \x01(\x03R\x10memoryUsageBytes\x12-\n" +
	"\x12active_connections\x18\t \x01(\x05R\x11activeConnections\"\xbd\x01\n" +
	"\x0fComponentStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.ninaivalaigal.graphops.v1.HealthStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x120\n" +
	"\x14last_check_timestamp\x18\x04 \x01(\x03R\x12lastCheckTimestamp\"\x86\x02\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x12\x1b\n" +
	"\tsql_state\x18\x04 \x01(\tR\bsqlState\x12N\n" +
	"\acontext\x18\x05 \x03(\v24.ninaivalaigal.graphops.v1.ErrorDetails.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x02\n" +
	"\fQueryMetrics\x12\"\n" +
	"\rparse_time_ms\x18\x01 \x01(\x01R\vparseTimeMs\x12 \n" +
	"\fplan_time_ms\x18\x02 \x01(\x01R\n" +
	"planTimeMs\x12*\n" +
	"\x11execution_time_ms\x18\x03 \x01(\x01R\x0fexecutionTimeMs\x12!\n" +
	"\frows_scanned\x18\x04 \x01(\x03R\vrowsScanned\x12#\n" +
	"\rrows_returned\x18\x05 \x01(\x03R\frowsReturned\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x03R\x0fmemoryUsedBytes\x12\x1b\n" +
	"\tcache_hit\x18\a \x01(\bR\bcacheHit*\xa9\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_STATUS_SUCCESS\x10\x01\x12\x1a\n" +
	"\x16EXECUTION_STATUS_ERROR\x10\x02\x12\x1c\n" +
	"\x18EXECUTION_STATUS_TIMEOUT\x10\x03\x12\x1c\n" +
	"\x18EXECUTION_STATUS_PARTIAL\x10\x04*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\xbd\x03\n" +
	"\x0fGraphOpsService\x12c\n" +
	"\fExecuteQuery\x12(.ninaivalaigal.graphops.v1.CypherRequest\x1a).ninaivalaigal.graphops.v1.CypherResponse\x12r\n" +
	"\x11ExecuteQueryBatch\x12-.ninaivalaigal.graphops.v1.CypherBatchRequest\x1a..ninaivalaigal.graphops.v1.CypherBatchResponse\x12l\n" +
	"\vHealthCheck\x12-.ninaivalaigal.graphops.v1.HealthCheckRequest\x1a..ninaivalaigal.graphops.v1.HealthCheckResponse\x12c\n" +
	"\n" +
	"GetMetrics\x12).ninaivalaigal.graphops.v1.MetricsRequest\x1a*.ninaivalaigal.graphops.v1.MetricsResponseBLZJgithub.com/Arunosaur/ninaivalaigal/shared/contracts/graphops/v1;graphopsv1b\x06proto3"

var (
	file_graphops_v1_graphops_proto_rawDescOnce sync.Once
	file_graphops_v1_graphops_proto_rawDescData []byte
)

func file_graphops_v1_graphops_proto_rawDescGZIP() []byte {
	file_graphops_v1_graphops_proto_rawDescOnce.Do(func() {
		file_graphops_v1_graphops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graphops_v1_graphops_proto_rawDesc), len(file_graphops_v1_graphops_proto_rawDesc)))
	})
	return file_graphops_v1_graphops_proto_rawDescData
}

var file_graphops_v1_graphops_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_graphops_v1_graphops_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_graphops_v1_graphops_proto_goTypes = []any{
	(ExecutionStatus)(0),        // 0: ninaivalaigal.graphops.v1.ExecutionStatus
	(HealthStatus)(0),           // 1: ninaivalaigal.graphops.v1.HealthStatus
	(*CypherRequest)(nil),       // 2: ninaivalaigal.graphops.v1.CypherRequest
	(*CypherResponse)(nil),      // 3: ninaivalaigal.graphops.v1.CypherResponse
	(*CypherBatchRequest)(nil),  // 4: ninaivalaigal.graphops.v1.CypherBatchRequest
	(*CypherBatchResponse)(nil), // 5: ninaivalaigal.graphops.v1.CypherBatchResponse
	(*HealthCheckRequest)(nil),  // 6: ninaivalaigal.graphops.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: ninaivalaigal.graphops.v1.HealthCheckResponse
	(*MetricsRequest)(nil),      // 8: ninaivalaigal.graphops.v1.MetricsRequest
	(*MetricsResponse)(nil),     // 9: ninaivalaigal.graphops.v1.MetricsResponse
	(*ComponentStatus)(nil),     // 10: ninaivalaigal.graphops.v1.ComponentStatus
	(*ErrorDetails)(nil),        // 11: ninaivalaigal.graphops.v1.ErrorDetails
	(*QueryMetrics)(nil),        // 12: ninaivalaigal.graphops.v1.QueryMetrics
	nil,                         // 13: ninaivalaigal.graphops.v1.CypherRequest.ParametersEntry
	nil,                         // 14: ninaivalaigal.graphops.v1.HealthCheckResponse.DetailsEntry
	nil,                         // 15: ninaivalaigal.graphops.v1.ErrorDetails.ContextEntry
}
var file_graphops_v1_graphops_proto_depIdxs = []int32{
	13, // 0: ninaivalaigal.graphops.v1.CypherRequest.parameters:type_name -> ninaivalaigal.graphops.v1.CypherRequest.ParametersEntry
	0,  // 1: ninaivalaigal.graphops.v1.CypherResponse.status:type_name -> ninaivalaigal.graphops.v1.ExecutionStatus
	11, // 2: ninaivalaigal.graphops.v1.CypherResponse.error:type_name -> ninaivalaigal.graphops.v1.ErrorDetails
	12, // 3: ninaivalaigal.graphops.v1.CypherResponse.metrics:type_name -> ninaivalaigal.graphops.v1.QueryMetrics
	2,  // 4: ninaivalaigal.graphops.v1.CypherBatchRequest.queries:type_name -> ninaivalaigal.graphops.v1.CypherRequest
	3,  // 5: ninaivalaigal.graphops.v1.CypherBatchResponse.responses:type_name -> ninaivalaigal.graphops.v1.CypherResponse
	0,  // 6: ninaivalaigal.graphops.v1.CypherBatchResponse.batch_status:type_name -> ninaivalaigal.graphops.v1.ExecutionStatus
	1,  // 7: ninaivalaigal.graphops.v1.HealthCheckResponse.status:type_name -> ninaivalaigal.graphops.v1.HealthStatus
	10, // 8: ninaivalaigal.graphops.v1.HealthCheckResponse.database:type_name -> ninaivalaigal.graphops.v1.ComponentStatus
	10, // 9: ninaivalaigal.graphops.v1.HealthCheckResponse.age_extension:type_name -> ninaivalaigal.graphops.v1.ComponentStatus
	14, // 10: ninaivalaigal.graphops.v1.HealthCheckResponse.details:type_name -> ninaivalaigal.graphops.v1.HealthCheckResponse.DetailsEntry
	1,  // 11: ninaivalaigal.graphops.v1.ComponentStatus.status:type_name -> ninaivalaigal.graphops.v1.HealthStatus
	15, // 12: ninaivalaigal.graphops.v1.ErrorDetails.context:type_name -> ninaivalaigal.graphops.v1.ErrorDetails.ContextEntry
	2,  // 13: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQuery:input_type -> ninaivalaigal.graphops.v1.CypherRequest
	4,  // 14: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQueryBatch:input_type -> ninaivalaigal.graphops.v1.CypherBatchRequest
	6,  // 15: ninaivalaigal.graphops.v1.GraphOpsService.HealthCheck:input_type -> ninaivalaigal.graphops.v1.HealthCheckRequest
	8,  // 16: ninaivalaigal.graphops.v1.GraphOpsService.GetMetrics:input_type -> ninaivalaigal.graphops.v1.MetricsRequest
	3,  // 17: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQuery:output_type -> ninaivalaigal.graphops.v1.CypherResponse
	5,  // 18: ninaivalaigal.graphops.v1.GraphOpsService.ExecuteQueryBatch:output_type -> ninaivalaigal.graphops.v1.CypherBatchResponse
	7,  // 19: ninaivalaigal.graphops.v1.GraphOpsService.HealthCheck:output_type -> ninaivalaigal.graphops.v1.HealthCheckResponse
	9,  // 20: ninaivalaigal.graphops.v1.GraphOpsService.GetMetrics:output_type -> ninaivalaigal.graphops.v1.MetricsResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_graphops_v1_graphops_proto_init() }
func file_graphops_v1_graphops_proto_init() {
	if File_graphops_v1_graphops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphops_v1_graphops_proto_rawDesc), len(file_graphops_v1_graphops_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graphops_v1_graphops_proto_goTypes,
		DependencyIndexes: file_graphops_v1_graphops_proto_depIdxs,
		EnumInfos:         file_graphops_v1_graphops_proto_enumTypes,
		MessageInfos:      file_graphops_v1_graphops_proto_msgTypes,
	}.Build()
	File_graphops_v1_graphops_proto = out.File
	file_graphops_v1_graphops_proto_goTypes = nil
	file_graphops_v1_graphops_proto_depIdxs = nil
}
