#!/usr/bin/env python3
# SPDX-License-Identifier: Proprietary
# Copyright (c) 2025 Medhasys LLC
#
# This file contains proprietary code owned by Medhasys LLC.
# Unauthorized copying, modification, or distribution is prohibited.
# See LICENSE file in the server/ directory for details.
#
"""
PDF Comparison Script - US#241
Compare PDFs generated by old and new invoice services to ensure byte-identical output

Usage:
    python scripts/compare_invoice_pdfs.py --count 100 --output results.json
"""

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime
from typing import Dict, List

# Add server to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "server"))

from server.billing_engine_integration_api import generate_invoice_pdf as generate_old
from server.invoice_management_api import create_pdf_invoice as create_old
from server.services import InvoicingService, TaxCalculator


def generate_new_pdf(invoice_data: Dict) -> bytes:
    """Generate PDF using new InvoicingService"""
    service = InvoicingService(tax_calculator=TaxCalculator())

    # Transform to new format if needed
    transformed = {
        "invoice_number": invoice_data.get("invoice_number", "INV-001"),
        "created_at": invoice_data.get("created_at", datetime.utcnow()),
        "issue_date": invoice_data.get("created_at", datetime.utcnow()),
        "due_date": invoice_data.get("due_date", datetime.utcnow()),
        "team_name": invoice_data.get("team_name", "Test Team"),
        "billing_email": invoice_data.get("billing_email", "test@example.com"),
        "team_id": invoice_data.get("team_id", "team-123"),
        "line_items": invoice_data.get("line_items", []),
        "subtotal": invoice_data.get("subtotal", 0.0),
        "tax_amount": invoice_data.get("tax_amount", 0.0),
        "total_amount": invoice_data.get("total_amount", 0.0),
        "status": invoice_data.get("status", "open"),
    }

    return service.generate_pdf(transformed)


def calculate_pdf_hash(pdf_bytes: bytes) -> str:
    """Calculate SHA256 hash of PDF"""
    return hashlib.sha256(pdf_bytes).hexdigest()


def generate_sample_invoices(count: int) -> List[Dict]:
    """Generate sample invoice data for testing"""
    invoices = []

    for i in range(count):
        invoice_data = {
            "invoice_number": f"INV-202501-{i:04d}",
            "created_at": datetime(2025, 1, 15),
            "due_date": datetime(2025, 2, 15),
            "team_name": f"Test Team {i}",
            "billing_email": f"test{i}@example.com",
            "team_id": f"team-{i:04d}",
            "line_items": [
                {
                    "description": f"Service {j}",
                    "quantity": j + 1,
                    "unit_price": 10.0 * (j + 1),
                    "total_price": 10.0 * (j + 1) * (j + 1),
                }
                for j in range(min(5, i % 10 + 1))  # Vary line item count
            ],
            "subtotal": sum(
                item["total_price"]
                for item in [
                    {
                        "description": f"Service {j}",
                        "quantity": j + 1,
                        "unit_price": 10.0 * (j + 1),
                        "total_price": 10.0 * (j + 1) * (j + 1),
                    }
                    for j in range(min(5, i % 10 + 1))
                ]
            ),
            "tax_amount": 0.0,
            "total_amount": 0.0,
            "status": "open" if i % 2 == 0 else "paid",
        }

        # Calculate tax
        tax_calc = TaxCalculator()
        invoice_data["tax_amount"] = tax_calc.calculate(
            subtotal=invoice_data["subtotal"],
            country="US",
            state=["CA", "NY", "TX", "FL"][i % 4],  # Rotate states
        )
        invoice_data["total_amount"] = invoice_data["subtotal"] + invoice_data["tax_amount"]

        invoices.append(invoice_data)

    return invoices


def compare_invoices(invoice_data: Dict, use_spec027: bool = False) -> Dict:
    """Compare old and new PDF generation for a single invoice"""
    result = {
        "invoice_number": invoice_data.get("invoice_number"),
        "match": False,
        "old_hash": None,
        "new_hash": None,
        "old_size": 0,
        "new_size": 0,
        "error": None,
    }

    try:
        # Generate old PDF (SPEC-027 or SPEC-028)
        if use_spec027:
            old_pdf = generate_old(invoice_data)
        else:
            # For SPEC-028, need to create Invoice object
            from server.invoice_management_api import (
                Invoice,
                InvoiceLineItem,
                TaxSettings,
            )

            line_items = [
                InvoiceLineItem(
                    description=item["description"],
                    quantity=item["quantity"],
                    unit_price=item["unit_price"],
                    total_price=item["total_price"],
                    period_start=invoice_data.get("period_start", datetime.utcnow()),
                    period_end=invoice_data.get("period_end", datetime.utcnow()),
                )
                for item in invoice_data.get("line_items", [])
            ]

            invoice = Invoice(
                invoice_number=invoice_data["invoice_number"],
                team_id=invoice_data["team_id"],
                team_name=invoice_data["team_name"],
                billing_email=invoice_data["billing_email"],
                issue_date=invoice_data.get("issue_date", invoice_data.get("created_at", datetime.utcnow())),
                due_date=invoice_data["due_date"],
                period_start=invoice_data.get("period_start", datetime.utcnow()),
                period_end=invoice_data.get("period_end", datetime.utcnow()),
                line_items=line_items,
                subtotal=invoice_data["subtotal"],
                tax_amount=invoice_data["tax_amount"],
                total_amount=invoice_data["total_amount"],
                status=invoice_data.get("status", "open"),
            )

            tax_settings = (
                TaxSettings(
                    tax_rate=invoice_data.get("tax_rate", 8.75),
                    tax_name="Sales Tax",
                )
                if invoice_data.get("tax_amount", 0) > 0
                else None
            )

            old_pdf = create_old(invoice, tax_settings)

        # Generate new PDF
        new_pdf = generate_new_pdf(invoice_data)

        # Compare
        result["old_hash"] = calculate_pdf_hash(old_pdf)
        result["new_hash"] = calculate_pdf_hash(new_pdf)
        result["old_size"] = len(old_pdf)
        result["new_size"] = len(new_pdf)
        result["match"] = result["old_hash"] == result["new_hash"]

    except Exception as e:
        result["error"] = str(e)
        result["match"] = False

    return result


def main():
    parser = argparse.ArgumentParser(description="Compare old and new invoice PDF generation")
    parser.add_argument(
        "--count",
        type=int,
        default=100,
        help="Number of invoices to generate and compare (default: 100)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="invoice_comparison_results.json",
        help="Output file for results (default: invoice_comparison_results.json)",
    )
    parser.add_argument(
        "--spec027",
        action="store_true",
        help="Use SPEC-027 format (billing_engine_integration_api) instead of SPEC-028",
    )

    args = parser.parse_args()

    print("=" * 70)
    print("Invoice PDF Comparison Script")
    print("=" * 70)
    print(f"Generating {args.count} sample invoices...")
    print(f"Using format: {'SPEC-027' if args.spec027 else 'SPEC-028'}")
    print()

    # Generate sample invoices
    invoices = generate_sample_invoices(args.count)
    print(f"✓ Generated {len(invoices)} sample invoices")
    print()

    print("Comparing PDFs (old vs new)...")
    print("-" * 70)

    results = []
    matches = 0
    mismatches = 0
    errors = 0

    for i, invoice_data in enumerate(invoices, 1):
        if i % 10 == 0:
            print(f"Progress: {i}/{len(invoices)} invoices compared...")

        result = compare_invoices(invoice_data, use_spec027=args.spec027)
        results.append(result)

        if result["error"]:
            errors += 1
            print(f"  ✗ {result['invoice_number']}: ERROR - {result['error']}")
        elif result["match"]:
            matches += 1
        else:
            mismatches += 1
            print(f"  ⚠ {result['invoice_number']}: MISMATCH")
            print(f"     Old: {result['old_hash'][:16]}... ({result['old_size']} bytes)")
            print(f"     New: {result['new_hash'][:16]}... ({result['new_size']} bytes)")

    print()
    print("=" * 70)
    print("COMPARISON RESULTS")
    print("=" * 70)
    print(f"Total Invoices: {len(results)}")
    print(f"✓ Matches: {matches} ({matches/len(results)*100:.1f}%)")
    print(f"⚠ Mismatches: {mismatches} ({mismatches/len(results)*100:.1f}%)")
    print(f"✗ Errors: {errors} ({errors/len(results)*100:.1f}%)")
    print()

    # Save results
    output_data = {
        "timestamp": datetime.utcnow().isoformat(),
        "total_invoices": len(results),
        "matches": matches,
        "mismatches": mismatches,
        "errors": errors,
        "match_rate": matches / len(results) * 100 if results else 0,
        "spec_format": "SPEC-027" if args.spec027 else "SPEC-028",
        "results": results,
    }

    with open(args.output, "w") as f:
        json.dump(output_data, f, indent=2, default=str)

    print(f"Results saved to: {args.output}")
    print("=" * 70)

    # Exit with error code if mismatches found
    if mismatches > 0 or errors > 0:
        sys.exit(1)

    print("✓ All PDFs match!")
    sys.exit(0)


if __name__ == "__main__":
    main()
