#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Medhasys LLC
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from admin.v1 import admin_pb2 as admin_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in admin/v1/admin_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AdminServiceStub(object):
    """Admin service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
            "/admin.v1.AdminService/ListUsers",
            request_serializer=admin_dot_v1_dot_admin__pb2.ListUsersRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.UserList.FromString,
            _registered_method=True,
        )
        self.GetUser = channel.unary_unary(
            "/admin.v1.AdminService/GetUser",
            request_serializer=admin_dot_v1_dot_admin__pb2.GetUserRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.UserDetails.FromString,
            _registered_method=True,
        )
        self.UpdateUser = channel.unary_unary(
            "/admin.v1.AdminService/UpdateUser",
            request_serializer=admin_dot_v1_dot_admin__pb2.UpdateUserRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.UserDetails.FromString,
            _registered_method=True,
        )
        self.SuspendUser = channel.unary_unary(
            "/admin.v1.AdminService/SuspendUser",
            request_serializer=admin_dot_v1_dot_admin__pb2.SuspendUserRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.SuspendUserResponse.FromString,
            _registered_method=True,
        )
        self.ListOrganizations = channel.unary_unary(
            "/admin.v1.AdminService/ListOrganizations",
            request_serializer=admin_dot_v1_dot_admin__pb2.ListOrganizationsRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.OrganizationList.FromString,
            _registered_method=True,
        )
        self.GetSystemMetrics = channel.unary_unary(
            "/admin.v1.AdminService/GetSystemMetrics",
            request_serializer=admin_dot_v1_dot_admin__pb2.GetSystemMetricsRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.SystemMetrics.FromString,
            _registered_method=True,
        )
        self.GetAuditLogs = channel.unary_unary(
            "/admin.v1.AdminService/GetAuditLogs",
            request_serializer=admin_dot_v1_dot_admin__pb2.GetAuditLogsRequest.SerializeToString,
            response_deserializer=admin_dot_v1_dot_admin__pb2.AuditLogList.FromString,
            _registered_method=True,
        )


class AdminServiceServicer(object):
    """Admin service"""

    def ListUsers(self, request, context):
        """List all users"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUser(self, request, context):
        """Get user details"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateUser(self, request, context):
        """Update user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SuspendUser(self, request, context):
        """Suspend user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListOrganizations(self, request, context):
        """List all organizations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSystemMetrics(self, request, context):
        """Get system metrics"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAuditLogs(self, request, context):
        """Get audit logs"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListUsers": grpc.unary_unary_rpc_method_handler(
            servicer.ListUsers,
            request_deserializer=admin_dot_v1_dot_admin__pb2.ListUsersRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.UserList.SerializeToString,
        ),
        "GetUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=admin_dot_v1_dot_admin__pb2.GetUserRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.UserDetails.SerializeToString,
        ),
        "UpdateUser": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateUser,
            request_deserializer=admin_dot_v1_dot_admin__pb2.UpdateUserRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.UserDetails.SerializeToString,
        ),
        "SuspendUser": grpc.unary_unary_rpc_method_handler(
            servicer.SuspendUser,
            request_deserializer=admin_dot_v1_dot_admin__pb2.SuspendUserRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.SuspendUserResponse.SerializeToString,
        ),
        "ListOrganizations": grpc.unary_unary_rpc_method_handler(
            servicer.ListOrganizations,
            request_deserializer=admin_dot_v1_dot_admin__pb2.ListOrganizationsRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.OrganizationList.SerializeToString,
        ),
        "GetSystemMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetSystemMetrics,
            request_deserializer=admin_dot_v1_dot_admin__pb2.GetSystemMetricsRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.SystemMetrics.SerializeToString,
        ),
        "GetAuditLogs": grpc.unary_unary_rpc_method_handler(
            servicer.GetAuditLogs,
            request_deserializer=admin_dot_v1_dot_admin__pb2.GetAuditLogsRequest.FromString,
            response_serializer=admin_dot_v1_dot_admin__pb2.AuditLogList.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("admin.v1.AdminService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("admin.v1.AdminService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Admin service"""

    @staticmethod
    def ListUsers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/ListUsers",
            admin_dot_v1_dot_admin__pb2.ListUsersRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/GetUser",
            admin_dot_v1_dot_admin__pb2.GetUserRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.UserDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/UpdateUser",
            admin_dot_v1_dot_admin__pb2.UpdateUserRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.UserDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SuspendUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/SuspendUser",
            admin_dot_v1_dot_admin__pb2.SuspendUserRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.SuspendUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListOrganizations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/ListOrganizations",
            admin_dot_v1_dot_admin__pb2.ListOrganizationsRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.OrganizationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSystemMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/GetSystemMetrics",
            admin_dot_v1_dot_admin__pb2.GetSystemMetricsRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.SystemMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAuditLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.v1.AdminService/GetAuditLogs",
            admin_dot_v1_dot_admin__pb2.GetAuditLogsRequest.SerializeToString,
            admin_dot_v1_dot_admin__pb2.AuditLogList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
