name: Pre-commit (Reusable)

on:
  workflow_call: {}
  workflow_dispatch: {}  # optional: lets you click "Run workflow"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: [self-hosted, macstudio]
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use conda nina
        uses: ./.github/actions/use-conda-nina

      - name: Pre-commit (nina)
        shell: bash
        run: |
          pre-commit install --install-hooks
          pre-commit run --all-files --show-diff-on-failure
